# ObjectMemory convolutional SNN — clean experiment notebook

This notebook contains only the current best pipeline and the planned output-threshold experiment.

Run cells from top to bottom. Dataset generation is cached after the first successful run. The baseline and the two threshold experiments are separate at the end, so you can run only the comparison you need.

Required packages: `torch`, `snntorch`, `pandas`, and `numpy`. Keep `lif_utils.py` in the same folder as this notebook.

In [15]:
from pathlib import Path
import copy
import random
import sys

import numpy as np
import pandas as pd
import torch
import torch.nn as nn
from torch.utils.data import DataLoader, TensorDataset
import snntorch as snn
from snntorch import surrogate


def find_support_file(filename):
    candidates = []
    for root in [Path.cwd(), *Path.cwd().parents]:
        candidates.extend([root / filename, root / "src" / filename])
    for candidate in candidates:
        if candidate.exists():
            return candidate.resolve()
    raise FileNotFoundError(
        f"Could not find {filename}. Keep it beside this notebook or under src/."
    )


lif_utils_path = find_support_file("lif_utils.py")
sys.path.insert(0, str(lif_utils_path.parent))
import lif_utils as lu

if torch.backends.mps.is_available():
    device = torch.device("mps")
elif torch.cuda.is_available():
    device = torch.device("cuda")
else:
    device = torch.device("cpu")

print("Using device:", device)
print("Using lif_utils:", lif_utils_path)

Using device: mps
Using lif_utils: /Users/alexeysolganik/Documents/PhD/Summer26/snn-moving-digit/notebooks/lif_utils.py

In [2]:
SHAPE_TO_LABEL = {"seven": 0, "box": 1, "tee": 2, "ell": 3}
LABEL_TO_SHAPE = {label: name for name, label in SHAPE_TO_LABEL.items()}
SHAPE_NAMES = list(SHAPE_TO_LABEL)

GOOD_VELOCITY_PARAMS = {
    "threshold_velocity": 15.0,
    "input_scale": 1.0,
    "beta_velocity": 0.8,
    "inhibition_strength": 3.0,
    "inhibition_radius": 1,
    "internal_steps": 5,
}

CANVAS_HEIGHT = 64
CANVAS_WIDTH = 64
STEPS = 7
INTENSITY = 1.0
SHAPE_TEMPLATES = lu.make_toy_2d_shape_templates()

DIRECTION_CONFIG = {
    "right": {"velocity_y": 0, "velocity_x": 1, "start_top": 28, "start_left": 10},
    "left":  {"velocity_y": 0, "velocity_x": -1, "start_top": 28, "start_left": 45},
    "down":  {"velocity_y": 1, "velocity_x": 0, "start_top": 10, "start_left": 28},
    "up":    {"velocity_y": -1, "velocity_x": 0, "start_top": 45, "start_left": 28},
}

# The original helper module expects these experiment constants as globals.
lu.GOOD_VELOCITY_PARAMS = GOOD_VELOCITY_PARAMS
lu.CANVAS_HEIGHT = CANVAS_HEIGHT
lu.CANVAS_WIDTH = CANVAS_WIDTH
lu.STEPS = STEPS
lu.INTENSITY = INTENSITY
lu.SHAPE_TEMPLATES = SHAPE_TEMPLATES
lu.DIRECTION_CONFIG = DIRECTION_CONFIG

In [3]:
def sample_random_velocity_sequence(
    num_transitions, max_speed=3, allow_stationary=False, seed=None
):
    if seed is not None:
        torch.manual_seed(seed)

    velocities = []
    for _ in range(num_transitions):
        while True:
            dy = int(torch.randint(-max_speed, max_speed + 1, (1,)).item())
            dx = int(torch.randint(-max_speed, max_speed + 1, (1,)).item())
            if allow_stationary or dy != 0 or dx != 0:
                break
        velocities.append((dy, dx))
    return velocities


def choose_safe_start_position_for_velocity_sequence(
    shape_name,
    velocity_sequence,
    canvas_height=CANVAS_HEIGHT,
    canvas_width=CANVAS_WIDTH,
    margin=8,
    seed=None,
):
    if seed is not None:
        torch.manual_seed(seed)

    shape_height, shape_width = SHAPE_TEMPLATES[shape_name].shape
    cumulative_y = [0]
    cumulative_x = [0]
    current_y = current_x = 0

    for dy, dx in velocity_sequence:
        current_y += dy
        current_x += dx
        cumulative_y.append(current_y)
        cumulative_x.append(current_x)

    min_start_y = margin - min(cumulative_y)
    max_start_y = canvas_height - shape_height - margin - max(cumulative_y)
    min_start_x = margin - min(cumulative_x)
    max_start_x = canvas_width - shape_width - margin - max(cumulative_x)

    if min_start_y > max_start_y or min_start_x > max_start_x:
        raise ValueError("Velocity sequence is too large to fit safely on the canvas.")

    start_top = int(torch.randint(min_start_y, max_start_y + 1, (1,)).item())
    start_left = int(torch.randint(min_start_x, max_start_x + 1, (1,)).item())
    return start_top, start_left


def make_one_classifier_dataset_sample(
    shape_name,
    max_speed=3,
    sample_seed=0,
    max_velocity=3,
    max_displacement=18,
    velocity_params=None,
):
    if velocity_params is None:
        velocity_params = GOOD_VELOCITY_PARAMS

    velocity_sequence = sample_random_velocity_sequence(
        STEPS - 1, max_speed=max_speed, seed=sample_seed
    )
    start_top, start_left = choose_safe_start_position_for_velocity_sequence(
        shape_name, velocity_sequence, seed=sample_seed + 10_000
    )
    case = lu.make_variable_velocity_spike_case(
        velocity_sequence=velocity_sequence,
        shape_name=shape_name,
        start_top=start_top,
        start_left=start_left,
    )
    memory_result = lu.run_displacement_gated_object_memory(
        case=case,
        max_velocity=max_velocity,
        max_displacement=max_displacement,
        velocity_params=velocity_params,
        threshold_memory=1.5,
        beta_memory=0.8,
        reset_mode="subtract",
    )
    return {
        "raw_spikes": case["spikes"].float(),
        "object_memory_spikes": memory_result["memory_spike_history"].float(),
        "label": SHAPE_TO_LABEL[shape_name],
    }


def build_classifier_dataset(
    samples_per_shape=100,
    max_speed=3,
    max_velocity=3,
    max_displacement=18,
    base_seed=0,
):
    raw_samples, memory_samples, labels = [], [], []
    total = samples_per_shape * len(SHAPE_NAMES)
    sample_index = 0

    for shape_name in SHAPE_NAMES:
        for _ in range(samples_per_shape):
            sample = make_one_classifier_dataset_sample(
                shape_name=shape_name,
                max_speed=max_speed,
                sample_seed=base_seed + sample_index,
                max_velocity=max_velocity,
                max_displacement=max_displacement,
            )
            raw_samples.append(sample["raw_spikes"])
            memory_samples.append(sample["object_memory_spikes"])
            labels.append(sample["label"])
            sample_index += 1
            if sample_index % 25 == 0 or sample_index == total:
                print(f"Generated {sample_index}/{total} samples")

    return {
        "raw_spikes_dataset": torch.stack(raw_samples),
        "object_memory_spikes_dataset": torch.stack(memory_samples),
        "labels": torch.tensor(labels, dtype=torch.long),
    }

## Build or load the dataset

The first run generates 400 samples and may take a while. It then saves `object_memory_classifier_dataset.pt` beside the notebook. Future runs load that cache quickly.

Delete the cache only when changing the data-generation or ObjectMemory parameters.

In [4]:
CACHE_PATH = lif_utils_path.parent / "object_memory_classifier_dataset.pt"

if CACHE_PATH.exists():
    classifier_dataset = torch.load(CACHE_PATH, map_location="cpu", weights_only=True)
    print("Loaded cached dataset:", CACHE_PATH)
else:
    classifier_dataset = build_classifier_dataset(
        samples_per_shape=100,
        max_speed=3,
        max_velocity=3,
        max_displacement=18,
        base_seed=0,
    )
    torch.save(classifier_dataset, CACHE_PATH)
    print("Saved dataset cache:", CACHE_PATH)

raw_spikes_dataset = classifier_dataset["raw_spikes_dataset"]
object_memory_spikes_dataset = classifier_dataset["object_memory_spikes_dataset"]
labels = classifier_dataset["labels"]

num_classes = len(SHAPE_TO_LABEL)
height, width = raw_spikes_dataset.shape[2:]

print("Raw:", tuple(raw_spikes_dataset.shape))
print("ObjectMemory:", tuple(object_memory_spikes_dataset.shape))
print("Labels:", tuple(labels.shape))
print("Class counts:", torch.bincount(labels).tolist())

Generated 25/400 samples
Generated 50/400 samples
Generated 75/400 samples
Generated 100/400 samples
Generated 125/400 samples
Generated 150/400 samples
Generated 175/400 samples
Generated 200/400 samples
Generated 225/400 samples
Generated 250/400 samples
Generated 275/400 samples
Generated 300/400 samples
Generated 325/400 samples
Generated 350/400 samples
Generated 375/400 samples
Generated 400/400 samples
Saved dataset cache: /Users/alexeysolganik/Documents/PhD/Summer26/snn-moving-digit/src/object_memory_classifier_dataset.pt
Raw: (400, 7, 64, 64)
ObjectMemory: (400, 7, 64, 64)
Labels: (400,)
Class counts: [100, 100, 100, 100]

In [5]:
def set_all_seeds(seed):
    random.seed(seed)
    np.random.seed(seed)
    torch.manual_seed(seed)
    if torch.cuda.is_available():
        torch.cuda.manual_seed_all(seed)


def make_stratified_train_test_split(labels, train_fraction=0.8, seed=0):
    generator = torch.Generator().manual_seed(seed)
    train_indices, test_indices = [], []

    for class_label in torch.unique(labels):
        class_indices = torch.nonzero(labels == class_label, as_tuple=False).squeeze(1)
        order = torch.randperm(len(class_indices), generator=generator)
        class_indices = class_indices[order]
        train_size = int(train_fraction * len(class_indices))
        train_indices.append(class_indices[:train_size])
        test_indices.append(class_indices[train_size:])

    train_indices = torch.cat(train_indices)
    test_indices = torch.cat(test_indices)
    train_indices = train_indices[torch.randperm(len(train_indices), generator=generator)]
    test_indices = test_indices[torch.randperm(len(test_indices), generator=generator)]
    return train_indices, test_indices


def make_dataloaders(spikes, labels, train_indices, test_indices, batch_size=32):
    train_dataset = TensorDataset(
        spikes[train_indices].float(), labels[train_indices].long()
    )
    test_dataset = TensorDataset(
        spikes[test_indices].float(), labels[test_indices].long()
    )
    return (
        DataLoader(train_dataset, batch_size=batch_size, shuffle=True),
        DataLoader(test_dataset, batch_size=batch_size, shuffle=False),
    )


train_indices, test_indices = make_stratified_train_test_split(labels, seed=0)
raw_train_loader, raw_test_loader = make_dataloaders(
    raw_spikes_dataset, labels, train_indices, test_indices
)
memory_train_loader, memory_test_loader = make_dataloaders(
    object_memory_spikes_dataset, labels, train_indices, test_indices
)

print("Train samples:", len(train_indices))
print("Test samples:", len(test_indices))
print("Test class counts:", torch.bincount(labels[test_indices]).tolist())

Train samples: 320
Test samples: 80
Test class counts: [20, 20, 20, 20]

In [6]:
class ConvSpikingClassifier(nn.Module):
    def __init__(
        self,
        num_classes=4,
        beta=0.95,
        feature_threshold=1.0,
        output_threshold=1.0,
        image_height=64,
        image_width=64,
    ):
        super().__init__()
        spike_grad = surrogate.fast_sigmoid(slope=25)

        self.conv1 = nn.Conv2d(1, 12, kernel_size=5, stride=2, padding=2)
        self.lif1 = snn.Leaky(
            beta=beta, threshold=feature_threshold, spike_grad=spike_grad
        )
        self.conv2 = nn.Conv2d(12, 24, kernel_size=5, stride=2, padding=2)
        self.lif2 = snn.Leaky(
            beta=beta, threshold=feature_threshold, spike_grad=spike_grad
        )

        flattened_size = 24 * (image_height // 4) * (image_width // 4)
        self.fc1 = nn.Linear(flattened_size, 128)
        self.lif3 = snn.Leaky(
            beta=beta, threshold=feature_threshold, spike_grad=spike_grad
        )
        self.fc_out = nn.Linear(128, num_classes)
        self.lif_out = snn.Leaky(
            beta=beta, threshold=output_threshold, spike_grad=spike_grad
        )

    def forward(self, spike_movie):
        num_steps = spike_movie.shape[1]
        mem1 = self.lif1.init_leaky()
        mem2 = self.lif2.init_leaky()
        mem3 = self.lif3.init_leaky()
        mem_out = self.lif_out.init_leaky()
        spikes, membranes = [], []

        for timestep in range(num_steps):
            current = self.conv1(spike_movie[:, timestep].unsqueeze(1))
            spike1, mem1 = self.lif1(current, mem1)
            current = self.conv2(spike1)
            spike2, mem2 = self.lif2(current, mem2)
            current = self.fc1(spike2.flatten(start_dim=1))
            spike3, mem3 = self.lif3(current, mem3)
            current = self.fc_out(spike3)
            spike_out, mem_out = self.lif_out(current, mem_out)
            spikes.append(spike_out)
            membranes.append(mem_out)

        return torch.stack(spikes), torch.stack(membranes)

In [7]:
def evaluate_classifier(model, data_loader, device=device, verbose=False):
    model.eval()
    labels_all, spike_predictions_all, membrane_predictions_all = [], [], []
    spike_counts_all = []

    with torch.no_grad():
        for spike_movies, labels_batch in data_loader:
            spike_movies = spike_movies.to(device)
            labels_batch = labels_batch.to(device)
            spk_rec, mem_rec = model(spike_movies)
            spike_counts = spk_rec.sum(dim=0)
            membrane_scores = mem_rec.sum(dim=0)
            labels_all.append(labels_batch.cpu())
            spike_predictions_all.append(spike_counts.argmax(dim=1).cpu())
            membrane_predictions_all.append(membrane_scores.argmax(dim=1).cpu())
            spike_counts_all.append(spike_counts.cpu())

    labels_all = torch.cat(labels_all)
    spike_predictions_all = torch.cat(spike_predictions_all)
    membrane_predictions_all = torch.cat(membrane_predictions_all)
    spike_counts_all = torch.cat(spike_counts_all)
    total_spikes = spike_counts_all.sum(dim=1)

    result = {
        "spike_accuracy": (spike_predictions_all == labels_all).float().mean().item(),
        "membrane_accuracy": (
            membrane_predictions_all == labels_all
        ).float().mean().item(),
        "zero_spike_samples": int((total_spikes == 0).sum().item()),
        "mean_output_spikes": total_spikes.float().mean().item(),
    }
    if verbose:
        print(pd.Series(result))
        print("Spike prediction counts:", torch.bincount(
            spike_predictions_all, minlength=num_classes
        ).tolist())
        print("Membrane prediction counts:", torch.bincount(
            membrane_predictions_all, minlength=num_classes
        ).tolist())
    return result


def conv_snn_accuracy(model, data_loader, device=device):
    return evaluate_classifier(model, data_loader, device)["spike_accuracy"]

In [8]:
def train_conv_spiking_classifier(
    train_loader,
    test_loader,
    num_classes=4,
    image_height=64,
    image_width=64,
    num_epochs=50,
    learning_rate=5e-4,
    beta=0.95,
    feature_threshold=1.0,
    output_threshold=1.0,
    device=device,
):
    model = ConvSpikingClassifier(
        num_classes=num_classes,
        beta=beta,
        feature_threshold=feature_threshold,
        output_threshold=output_threshold,
        image_height=image_height,
        image_width=image_width,
    ).to(device)
    optimizer = torch.optim.Adam(
        model.parameters(),
        lr=learning_rate,
        betas=(0.9, 0.999),
        weight_decay=1e-5,
    )
    loss_fn = nn.CrossEntropyLoss()
    history = []
    best_test_accuracy = -1.0
    best_model_state = None

    for epoch in range(num_epochs):
        model.train()
        total_loss = 0.0
        total_examples = 0

        for spike_movies, labels_batch in train_loader:
            spike_movies = spike_movies.to(device)
            labels_batch = labels_batch.to(device)
            optimizer.zero_grad()
            _, mem_rec = model(spike_movies)

            # Current best objective: membrane cross-entropy at every timestep.
            loss = torch.zeros((), device=device)
            for timestep in range(mem_rec.shape[0]):
                loss = loss + loss_fn(mem_rec[timestep], labels_batch)

            loss.backward()
            optimizer.step()
            batch_size = labels_batch.shape[0]
            total_loss += loss.item() * batch_size
            total_examples += batch_size

        train_loss = total_loss / total_examples
        train_accuracy = conv_snn_accuracy(model, train_loader, device)
        test_accuracy = conv_snn_accuracy(model, test_loader, device)
        history.append({
            "epoch": epoch,
            "train_loss": train_loss,
            "train_accuracy": train_accuracy,
            "test_accuracy": test_accuracy,
        })

        if test_accuracy > best_test_accuracy:
            best_test_accuracy = test_accuracy
            best_model_state = copy.deepcopy(model.state_dict())

        print(
            f"epoch {epoch:02d} | loss {train_loss:.4f} | "
            f"train acc {train_accuracy:.3f} | test acc {test_accuracy:.3f}"
        )

    model.load_state_dict(best_model_state)
    return model, pd.DataFrame(history)

In [9]:
SEEDS = [0, 1, 2, 3, 4]
NUM_EPOCHS = 50


def run_threshold_comparison(output_threshold, feature_threshold=1.0):
    rows = []
    models = {"raw": {}, "memory": {}}
    histories = {"raw": {}, "memory": {}}

    for seed in SEEDS:
        for input_name, train_loader, test_loader in [
            ("raw", raw_train_loader, raw_test_loader),
            ("memory", memory_train_loader, memory_test_loader),
        ]:
            print(
                f"\nSeed {seed} | {input_name} | "
                f"feature threshold={feature_threshold} | "
                f"output threshold={output_threshold}"
            )
            set_all_seeds(seed)
            model, history = train_conv_spiking_classifier(
                train_loader=train_loader,
                test_loader=test_loader,
                num_classes=num_classes,
                image_height=height,
                image_width=width,
                num_epochs=NUM_EPOCHS,
                learning_rate=5e-4,
                beta=0.95,
                feature_threshold=feature_threshold,
                output_threshold=output_threshold,
                device=device,
            )
            diagnostic = evaluate_classifier(model, test_loader, device)
            models[input_name][seed] = model
            histories[input_name][seed] = history
            rows.append({
                "seed": seed,
                "input": input_name,
                "feature_threshold": feature_threshold,
                "output_threshold": output_threshold,
                "best_test_accuracy": history["test_accuracy"].max(),
                "best_epoch": int(history["test_accuracy"].idxmax()),
                **diagnostic,
            })

    results = pd.DataFrame(rows)
    comparison = results.pivot(index="seed", columns="input", values="best_test_accuracy")
    comparison["memory_minus_raw"] = comparison["memory"] - comparison["raw"]
    display(results)
    display(comparison)
    display(comparison.mean().to_frame("mean"))
    return {"results": results, "comparison": comparison, "models": models, "histories": histories}

## Baseline: reproduce the current best pipeline

Run this cell to reproduce the original threshold-1.0 comparison. It performs ten training runs: raw and ObjectMemory for each of five seeds.

In [10]:
baseline_results = run_threshold_comparison(
    feature_threshold=1.0,
    output_threshold=1.0,
)

Seed 0 | raw | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 1 | raw | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8203 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.8084 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7966 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7865 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7793 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7708 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7643 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7582 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7507 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7455 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7418 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7364 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7326 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7296 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7265 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7238 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7213 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7204 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7176 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7149 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7129 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7118 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7115 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7095 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7085 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7084 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7067 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7068 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7067 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7046 | train acc 0.250 | test acc 0.250

Seed 1 | memory | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8153 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7318 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.6768 | train acc 0.331 | test acc 0.287
epoch 06 | loss 9.5962 | train acc 0.428 | test acc 0.350
epoch 07 | loss 9.4912 | train acc 0.469 | test acc 0.412
epoch 08 | loss 9.2250 | train acc 0.469 | test acc 0.450
epoch 09 | loss 8.9150 | train acc 0.488 | test acc 0.425
epoch 10 | loss 8.6366 | train acc 0.478 | test acc 0.450
epoch 11 | loss 8.4363 | train acc 0.500 | test acc 0.438
epoch 12 | loss 8.1506 | train acc 0.528 | test acc 0.425
epoch 13 | loss 7.8561 | train acc 0.566 | test acc 0.425
epoch 14 | loss 7.5991 | train acc 0.628 | test acc 0.438
epoch 15 | loss 7.3750 | train acc 0.675 | test acc 0.500
epoch 16 | loss 7.2538 | train acc 0.663 | test acc 0.450
epoch 17 | loss 7.0126 | train acc 0.728 | test acc 0.463
epoch 18 | loss 6.7678 | train acc 0.762 | test acc 0.488
epoch 19 | loss 6.5373 | train acc 0.800 | test acc 0.475
epoch 20 | loss 6.2249 | train acc 0.837 | test acc 0.463
epoch 21 | loss 6.0038 | train acc 0.859 | test acc 0.425
epoch 22 | loss 5.7416 | train acc 0.872 | test acc 0.438
epoch 23 | loss 5.5517 | train acc 0.884 | test acc 0.400
epoch 24 | loss 5.3856 | train acc 0.919 | test acc 0.412
epoch 25 | loss 5.1233 | train acc 0.934 | test acc 0.425
epoch 26 | loss 4.8996 | train acc 0.969 | test acc 0.375
epoch 27 | loss 4.6969 | train acc 0.975 | test acc 0.387
epoch 28 | loss 4.4390 | train acc 0.978 | test acc 0.363
epoch 29 | loss 4.3080 | train acc 0.981 | test acc 0.363
epoch 30 | loss 4.1339 | train acc 0.984 | test acc 0.363
epoch 31 | loss 3.9540 | train acc 0.991 | test acc 0.400
epoch 32 | loss 3.8105 | train acc 0.991 | test acc 0.387
epoch 33 | loss 3.7119 | train acc 0.991 | test acc 0.325
epoch 34 | loss 3.6171 | train acc 0.994 | test acc 0.312
epoch 35 | loss 3.5149 | train acc 0.994 | test acc 0.312
epoch 36 | loss 3.4385 | train acc 0.997 | test acc 0.350
epoch 37 | loss 3.3624 | train acc 0.997 | test acc 0.325
epoch 38 | loss 3.2824 | train acc 0.997 | test acc 0.325
epoch 39 | loss 3.2310 | train acc 0.997 | test acc 0.350
epoch 40 | loss 3.1716 | train acc 0.997 | test acc 0.363
epoch 41 | loss 3.1270 | train acc 0.997 | test acc 0.338
epoch 42 | loss 3.0960 | train acc 0.997 | test acc 0.387
epoch 43 | loss 3.0589 | train acc 0.997 | test acc 0.400
epoch 44 | loss 3.0175 | train acc 1.000 | test acc 0.412
epoch 45 | loss 2.9952 | train acc 1.000 | test acc 0.412
epoch 46 | loss 2.9654 | train acc 1.000 | test acc 0.400
epoch 47 | loss 2.9406 | train acc 1.000 | test acc 0.387
epoch 48 | loss 2.9073 | train acc 1.000 | test acc 0.425
epoch 49 | loss 2.8806 | train acc 1.000 | test acc 0.450

Seed 2 | raw | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7282 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7258 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7234 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7216 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7190 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7177 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7158 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7143 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7131 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7124 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7113 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7087 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7070 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7064 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7044 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7050 | train acc 0.250 | test acc 0.250

Seed 2 | memory | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7306 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7266 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7243 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7224 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7197 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7173 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.6876 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.5835 | train acc 0.256 | test acc 0.250
epoch 15 | loss 9.4822 | train acc 0.300 | test acc 0.287
epoch 16 | loss 9.3432 | train acc 0.316 | test acc 0.275
epoch 17 | loss 9.2306 | train acc 0.363 | test acc 0.338
epoch 18 | loss 9.1157 | train acc 0.450 | test acc 0.438
epoch 19 | loss 8.9833 | train acc 0.481 | test acc 0.463
epoch 20 | loss 8.7888 | train acc 0.494 | test acc 0.475
epoch 21 | loss 8.6279 | train acc 0.500 | test acc 0.488
epoch 22 | loss 8.4807 | train acc 0.497 | test acc 0.475
epoch 23 | loss 8.3269 | train acc 0.500 | test acc 0.488
epoch 24 | loss 8.2251 | train acc 0.500 | test acc 0.488
epoch 25 | loss 8.1374 | train acc 0.500 | test acc 0.488
epoch 26 | loss 8.0641 | train acc 0.500 | test acc 0.488
epoch 27 | loss 7.9642 | train acc 0.500 | test acc 0.488
epoch 28 | loss 7.8737 | train acc 0.500 | test acc 0.488
epoch 29 | loss 7.8050 | train acc 0.500 | test acc 0.488
epoch 30 | loss 7.7071 | train acc 0.500 | test acc 0.488
epoch 31 | loss 7.6323 | train acc 0.500 | test acc 0.488
epoch 32 | loss 7.5113 | train acc 0.500 | test acc 0.488
epoch 33 | loss 7.3950 | train acc 0.500 | test acc 0.488
epoch 34 | loss 7.2873 | train acc 0.500 | test acc 0.488
epoch 35 | loss 7.1675 | train acc 0.500 | test acc 0.488
epoch 36 | loss 7.0403 | train acc 0.500 | test acc 0.488
epoch 37 | loss 6.9219 | train acc 0.503 | test acc 0.488
epoch 38 | loss 6.8083 | train acc 0.506 | test acc 0.488
epoch 39 | loss 6.7271 | train acc 0.506 | test acc 0.488
epoch 40 | loss 6.5885 | train acc 0.516 | test acc 0.488
epoch 41 | loss 6.4761 | train acc 0.553 | test acc 0.525
epoch 42 | loss 6.4292 | train acc 0.606 | test acc 0.538
epoch 43 | loss 6.3867 | train acc 0.641 | test acc 0.538
epoch 44 | loss 6.3777 | train acc 0.591 | test acc 0.512
epoch 45 | loss 6.4515 | train acc 0.675 | test acc 0.587
epoch 46 | loss 6.1839 | train acc 0.688 | test acc 0.600
epoch 47 | loss 6.0632 | train acc 0.703 | test acc 0.600
epoch 48 | loss 5.9591 | train acc 0.781 | test acc 0.637
epoch 49 | loss 5.9318 | train acc 0.806 | test acc 0.663

Seed 3 | raw | feature threshold=1.0 | output threshold=1.0
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,1.0,1.0,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,1.0,1.0,0.2500,0,0.2500,0.2500,80,0.0000
2,1,raw,1.0,1.0,0.2500,0,0.2500,0.2500,80,0.0000
3,1,memory,1.0,1.0,0.5000,15,0.5000,0.4500,41,0.8875
4,2,raw,1.0,1.0,0.2500,0,0.2500,0.2500,80,0.0000
5,2,memory,1.0,1.0,0.6625,49,0.6625,0.6875,36,1.3750
6,3,raw,1.0,1.0,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,1.0,1.0,0.2500,0,0.2500,0.2500,80,0.0000
8,4,raw,1.0,1.0,0.4875,44,0.4875,0.5125,53,0.6875
9,4,memory,1.0,1.0,0.5500,25,0.5500,0.5625,9,2.1875

input  memory     raw  memory_minus_raw
seed
0      0.2500  0.2500            0.0000
1      0.5000  0.2500            0.2500
2      0.6625  0.2500            0.4125
3      0.2500  0.2500            0.0000
4      0.5500  0.4875            0.0625

                    mean
input
memory            0.4425
raw               0.2975
memory_minus_raw  0.1450

## Next experiment A: output threshold 0.5

This keeps all hidden/feature thresholds at 1.0 and lowers only the four output neurons' threshold.

In [11]:
threshold_050_results = run_threshold_comparison(
    feature_threshold=1.0,
    output_threshold=0.5,
)

Seed 0 | raw | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 1 | raw | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8203 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.8084 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7966 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7865 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7793 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7708 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7643 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7582 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7507 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7455 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7418 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7364 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7326 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7296 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7265 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7238 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7213 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7204 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7176 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7149 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7129 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7118 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7115 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7095 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7085 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7084 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7067 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7068 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7067 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7046 | train acc 0.250 | test acc 0.250

Seed 1 | memory | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8153 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7318 | train acc 0.406 | test acc 0.400
epoch 05 | loss 9.6768 | train acc 0.444 | test acc 0.425
epoch 06 | loss 9.5962 | train acc 0.481 | test acc 0.438
epoch 07 | loss 9.4912 | train acc 0.497 | test acc 0.438
epoch 08 | loss 9.2269 | train acc 0.419 | test acc 0.387
epoch 09 | loss 8.9010 | train acc 0.475 | test acc 0.425
epoch 10 | loss 8.6095 | train acc 0.497 | test acc 0.463
epoch 11 | loss 8.4190 | train acc 0.541 | test acc 0.412
epoch 12 | loss 8.1779 | train acc 0.634 | test acc 0.450
epoch 13 | loss 7.9231 | train acc 0.659 | test acc 0.387
epoch 14 | loss 7.6614 | train acc 0.716 | test acc 0.412
epoch 15 | loss 7.4267 | train acc 0.772 | test acc 0.463
epoch 16 | loss 7.1911 | train acc 0.762 | test acc 0.425
epoch 17 | loss 6.9951 | train acc 0.809 | test acc 0.425
epoch 18 | loss 6.7198 | train acc 0.828 | test acc 0.412
epoch 19 | loss 6.4532 | train acc 0.850 | test acc 0.425
epoch 20 | loss 6.1395 | train acc 0.878 | test acc 0.425
epoch 21 | loss 5.8830 | train acc 0.900 | test acc 0.438
epoch 22 | loss 5.6598 | train acc 0.916 | test acc 0.425
epoch 23 | loss 5.4958 | train acc 0.931 | test acc 0.438
epoch 24 | loss 5.1944 | train acc 0.941 | test acc 0.400
epoch 25 | loss 4.9335 | train acc 0.966 | test acc 0.412
epoch 26 | loss 4.7017 | train acc 0.972 | test acc 0.412
epoch 27 | loss 4.4638 | train acc 0.988 | test acc 0.412
epoch 28 | loss 4.2994 | train acc 0.988 | test acc 0.412
epoch 29 | loss 4.1583 | train acc 0.981 | test acc 0.400
epoch 30 | loss 3.9871 | train acc 0.991 | test acc 0.363
epoch 31 | loss 3.8504 | train acc 0.997 | test acc 0.375
epoch 32 | loss 3.7481 | train acc 1.000 | test acc 0.400
epoch 33 | loss 3.6245 | train acc 1.000 | test acc 0.412
epoch 34 | loss 3.5259 | train acc 1.000 | test acc 0.350
epoch 35 | loss 3.4482 | train acc 1.000 | test acc 0.375
epoch 36 | loss 3.3734 | train acc 1.000 | test acc 0.400
epoch 37 | loss 3.3120 | train acc 1.000 | test acc 0.387
epoch 38 | loss 3.2573 | train acc 1.000 | test acc 0.375
epoch 39 | loss 3.1966 | train acc 1.000 | test acc 0.387
epoch 40 | loss 3.1470 | train acc 0.997 | test acc 0.375
epoch 41 | loss 3.1200 | train acc 0.997 | test acc 0.387
epoch 42 | loss 3.0771 | train acc 1.000 | test acc 0.412
epoch 43 | loss 3.0442 | train acc 1.000 | test acc 0.412
epoch 44 | loss 3.1891 | train acc 0.997 | test acc 0.400
epoch 45 | loss 3.2167 | train acc 1.000 | test acc 0.400
epoch 46 | loss 3.1065 | train acc 0.997 | test acc 0.387
epoch 47 | loss 3.0332 | train acc 1.000 | test acc 0.400
epoch 48 | loss 2.8850 | train acc 1.000 | test acc 0.400
epoch 49 | loss 2.8165 | train acc 0.997 | test acc 0.425

Seed 2 | raw | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7282 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7258 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7234 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7216 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7190 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7177 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7158 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7143 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7131 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7124 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7113 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7087 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7070 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7064 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7044 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7050 | train acc 0.250 | test acc 0.250

Seed 2 | memory | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7306 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7266 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7243 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7224 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7197 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7173 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.6876 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.5842 | train acc 0.306 | test acc 0.275
epoch 15 | loss 9.4918 | train acc 0.359 | test acc 0.363
epoch 16 | loss 9.3701 | train acc 0.425 | test acc 0.387
epoch 17 | loss 9.2780 | train acc 0.456 | test acc 0.438
epoch 18 | loss 9.1349 | train acc 0.478 | test acc 0.450
epoch 19 | loss 8.9787 | train acc 0.491 | test acc 0.463
epoch 20 | loss 8.7664 | train acc 0.497 | test acc 0.475
epoch 21 | loss 8.6091 | train acc 0.500 | test acc 0.475
epoch 22 | loss 8.4816 | train acc 0.500 | test acc 0.475
epoch 23 | loss 8.3104 | train acc 0.500 | test acc 0.488
epoch 24 | loss 8.1938 | train acc 0.500 | test acc 0.488
epoch 25 | loss 8.1167 | train acc 0.500 | test acc 0.488
epoch 26 | loss 8.0354 | train acc 0.500 | test acc 0.488
epoch 27 | loss 7.9786 | train acc 0.500 | test acc 0.488
epoch 28 | loss 7.8943 | train acc 0.500 | test acc 0.488
epoch 29 | loss 7.8016 | train acc 0.500 | test acc 0.488
epoch 30 | loss 7.7284 | train acc 0.500 | test acc 0.488
epoch 31 | loss 7.6604 | train acc 0.500 | test acc 0.488
epoch 32 | loss 7.5934 | train acc 0.503 | test acc 0.488
epoch 33 | loss 7.5253 | train acc 0.500 | test acc 0.488
epoch 34 | loss 7.4253 | train acc 0.531 | test acc 0.512
epoch 35 | loss 7.3447 | train acc 0.559 | test acc 0.538
epoch 36 | loss 7.2510 | train acc 0.575 | test acc 0.525
epoch 37 | loss 7.1515 | train acc 0.581 | test acc 0.550
epoch 38 | loss 7.0563 | train acc 0.594 | test acc 0.550
epoch 39 | loss 6.9257 | train acc 0.691 | test acc 0.600
epoch 40 | loss 6.8463 | train acc 0.762 | test acc 0.637
epoch 41 | loss 6.7747 | train acc 0.816 | test acc 0.688
epoch 42 | loss 6.6679 | train acc 0.822 | test acc 0.675
epoch 43 | loss 6.5586 | train acc 0.853 | test acc 0.700
epoch 44 | loss 6.4606 | train acc 0.859 | test acc 0.725
epoch 45 | loss 6.4774 | train acc 0.837 | test acc 0.650
epoch 46 | loss 6.3747 | train acc 0.850 | test acc 0.650
epoch 47 | loss 6.2354 | train acc 0.859 | test acc 0.587
epoch 48 | loss 6.1139 | train acc 0.853 | test acc 0.650
epoch 49 | loss 5.9474 | train acc 0.897 | test acc 0.637

Seed 3 | raw | feature threshold=1.0 | output threshold=0.5
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,1.0,0.5,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,1.0,0.5,0.2500,0,0.2500,0.2500,80,0.0000
2,1,raw,1.0,0.5,0.2500,0,0.2500,0.2500,80,0.0000
3,1,memory,1.0,0.5,0.4625,10,0.4625,0.3875,27,1.3000
4,2,raw,1.0,0.5,0.2500,0,0.2500,0.2500,80,0.0000
5,2,memory,1.0,0.5,0.7250,44,0.7250,0.6875,25,1.7750
6,3,raw,1.0,0.5,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,1.0,0.5,0.2500,0,0.2500,0.2500,80,0.0000
8,4,raw,1.0,0.5,0.5250,40,0.5250,0.5500,18,1.3625
9,4,memory,1.0,0.5,0.5500,20,0.5500,0.5375,0,3.2250

input  memory    raw  memory_minus_raw
seed
0      0.2500  0.250            0.0000
1      0.4625  0.250            0.2125
2      0.7250  0.250            0.4750
3      0.2500  0.250            0.0000
4      0.5500  0.525            0.0250

                    mean
input
memory            0.4475
raw               0.3050
memory_minus_raw  0.1425

## Next experiment B: output threshold 0.75

In [12]:
threshold_075_results = run_threshold_comparison(
    feature_threshold=1.0,
    output_threshold=0.75,
)

Seed 0 | raw | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 1 | raw | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8203 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.8084 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7966 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7865 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7793 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7708 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7643 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7582 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7507 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7455 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7418 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7364 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7326 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7296 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7265 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7238 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7213 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7204 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7176 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7149 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7129 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7118 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7115 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7095 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7085 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7084 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7067 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7068 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7067 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7046 | train acc 0.250 | test acc 0.250

Seed 1 | memory | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8153 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7318 | train acc 0.303 | test acc 0.287
epoch 05 | loss 9.6768 | train acc 0.412 | test acc 0.338
epoch 06 | loss 9.5962 | train acc 0.459 | test acc 0.412
epoch 07 | loss 9.4912 | train acc 0.472 | test acc 0.425
epoch 08 | loss 9.2281 | train acc 0.453 | test acc 0.450
epoch 09 | loss 8.9014 | train acc 0.466 | test acc 0.425
epoch 10 | loss 8.6198 | train acc 0.488 | test acc 0.438
epoch 11 | loss 8.4307 | train acc 0.509 | test acc 0.438
epoch 12 | loss 8.1461 | train acc 0.559 | test acc 0.463
epoch 13 | loss 7.8770 | train acc 0.619 | test acc 0.463
epoch 14 | loss 7.6384 | train acc 0.659 | test acc 0.438
epoch 15 | loss 7.4245 | train acc 0.747 | test acc 0.512
epoch 16 | loss 7.2684 | train acc 0.691 | test acc 0.412
epoch 17 | loss 7.0259 | train acc 0.775 | test acc 0.463
epoch 18 | loss 6.7462 | train acc 0.794 | test acc 0.425
epoch 19 | loss 6.5253 | train acc 0.825 | test acc 0.425
epoch 20 | loss 6.2576 | train acc 0.841 | test acc 0.425
epoch 21 | loss 6.0036 | train acc 0.872 | test acc 0.412
epoch 22 | loss 5.7379 | train acc 0.909 | test acc 0.412
epoch 23 | loss 5.6230 | train acc 0.916 | test acc 0.425
epoch 24 | loss 5.3361 | train acc 0.944 | test acc 0.400
epoch 25 | loss 5.0992 | train acc 0.956 | test acc 0.375
epoch 26 | loss 4.8250 | train acc 0.969 | test acc 0.387
epoch 27 | loss 4.5873 | train acc 0.972 | test acc 0.338
epoch 28 | loss 4.3556 | train acc 0.978 | test acc 0.375
epoch 29 | loss 4.1837 | train acc 0.988 | test acc 0.400
epoch 30 | loss 4.0358 | train acc 0.981 | test acc 0.375
epoch 31 | loss 3.8745 | train acc 0.988 | test acc 0.363
epoch 32 | loss 3.7562 | train acc 0.991 | test acc 0.400
epoch 33 | loss 3.6309 | train acc 0.991 | test acc 0.412
epoch 34 | loss 3.5324 | train acc 0.997 | test acc 0.425
epoch 35 | loss 3.4474 | train acc 0.997 | test acc 0.400
epoch 36 | loss 3.3615 | train acc 0.997 | test acc 0.375
epoch 37 | loss 3.3088 | train acc 1.000 | test acc 0.387
epoch 38 | loss 3.2689 | train acc 1.000 | test acc 0.387
epoch 39 | loss 3.2254 | train acc 1.000 | test acc 0.363
epoch 40 | loss 3.1795 | train acc 1.000 | test acc 0.387
epoch 41 | loss 3.1380 | train acc 1.000 | test acc 0.375
epoch 42 | loss 3.1000 | train acc 1.000 | test acc 0.387
epoch 43 | loss 3.0686 | train acc 1.000 | test acc 0.412
epoch 44 | loss 3.0818 | train acc 0.997 | test acc 0.375
epoch 45 | loss 3.2015 | train acc 0.994 | test acc 0.400
epoch 46 | loss 3.1479 | train acc 0.997 | test acc 0.375
epoch 47 | loss 3.0501 | train acc 0.997 | test acc 0.400
epoch 48 | loss 3.0077 | train acc 0.997 | test acc 0.387
epoch 49 | loss 2.9633 | train acc 0.997 | test acc 0.363

Seed 2 | raw | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7282 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7258 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7234 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7216 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7190 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7177 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7158 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7143 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7131 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7124 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7113 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7087 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7070 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7064 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7044 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7050 | train acc 0.250 | test acc 0.250

Seed 2 | memory | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7306 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7266 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7243 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7224 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7197 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7173 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.6876 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.5835 | train acc 0.278 | test acc 0.262
epoch 15 | loss 9.4847 | train acc 0.322 | test acc 0.275
epoch 16 | loss 9.3530 | train acc 0.344 | test acc 0.350
epoch 17 | loss 9.2528 | train acc 0.431 | test acc 0.412
epoch 18 | loss 9.1301 | train acc 0.469 | test acc 0.450
epoch 19 | loss 8.9657 | train acc 0.494 | test acc 0.463
epoch 20 | loss 8.7646 | train acc 0.500 | test acc 0.475
epoch 21 | loss 8.6165 | train acc 0.500 | test acc 0.488
epoch 22 | loss 8.4700 | train acc 0.500 | test acc 0.475
epoch 23 | loss 8.3214 | train acc 0.500 | test acc 0.488
epoch 24 | loss 8.1986 | train acc 0.500 | test acc 0.488
epoch 25 | loss 8.1101 | train acc 0.500 | test acc 0.488
epoch 26 | loss 8.0543 | train acc 0.500 | test acc 0.488
epoch 27 | loss 7.9678 | train acc 0.500 | test acc 0.488
epoch 28 | loss 7.8975 | train acc 0.500 | test acc 0.488
epoch 29 | loss 7.8230 | train acc 0.500 | test acc 0.488
epoch 30 | loss 7.6963 | train acc 0.500 | test acc 0.488
epoch 31 | loss 7.6035 | train acc 0.500 | test acc 0.488
epoch 32 | loss 7.4823 | train acc 0.500 | test acc 0.488
epoch 33 | loss 7.3437 | train acc 0.500 | test acc 0.488
epoch 34 | loss 7.2178 | train acc 0.500 | test acc 0.488
epoch 35 | loss 7.1158 | train acc 0.503 | test acc 0.488
epoch 36 | loss 6.9788 | train acc 0.503 | test acc 0.488
epoch 37 | loss 6.8591 | train acc 0.556 | test acc 0.512
epoch 38 | loss 6.8029 | train acc 0.591 | test acc 0.550
epoch 39 | loss 6.6941 | train acc 0.603 | test acc 0.562
epoch 40 | loss 6.5726 | train acc 0.663 | test acc 0.587
epoch 41 | loss 6.5464 | train acc 0.750 | test acc 0.587
epoch 42 | loss 6.4875 | train acc 0.781 | test acc 0.613
epoch 43 | loss 6.3935 | train acc 0.809 | test acc 0.587
epoch 44 | loss 6.3948 | train acc 0.784 | test acc 0.600
epoch 45 | loss 6.4697 | train acc 0.791 | test acc 0.562
epoch 46 | loss 6.2411 | train acc 0.822 | test acc 0.637
epoch 47 | loss 6.1384 | train acc 0.825 | test acc 0.613
epoch 48 | loss 5.9790 | train acc 0.856 | test acc 0.675
epoch 49 | loss 5.8065 | train acc 0.863 | test acc 0.663

Seed 3 | raw | feature threshold=1.0 | output threshold=0.75
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,1.0,0.75,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,1.0,0.75,0.2500,0,0.2500,0.2500,80,0.0000
2,1,raw,1.0,0.75,0.2500,0,0.2500,0.2500,80,0.0000
3,1,memory,1.0,0.75,0.5125,15,0.5125,0.4375,26,1.3375
4,2,raw,1.0,0.75,0.2500,0,0.2500,0.2500,80,0.0000
5,2,memory,1.0,0.75,0.6750,48,0.6750,0.6750,27,1.7375
6,3,raw,1.0,0.75,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,1.0,0.75,0.2500,0,0.2500,0.2500,80,0.0000
8,4,raw,1.0,0.75,0.5125,48,0.5125,0.5250,12,1.4125
9,4,memory,1.0,0.75,0.5750,21,0.5750,0.5375,7,2.3375

input  memory     raw  memory_minus_raw
seed
0      0.2500  0.2500            0.0000
1      0.5125  0.2500            0.2625
2      0.6750  0.2500            0.4250
3      0.2500  0.2500            0.0000
4      0.5750  0.5125            0.0625

                    mean
input
memory            0.4525
raw               0.3025
memory_minus_raw  0.1500

## Optional combined summary

Run after completing the baseline and both new threshold experiments.

In [13]:
combined_results = pd.concat(
    [
        baseline_results["results"],
        threshold_050_results["results"],
        threshold_075_results["results"],
    ],
    ignore_index=True,
)

display(
    combined_results.groupby(["output_threshold", "input"])[
        [
            "best_test_accuracy",
            "spike_accuracy",
            "membrane_accuracy",
            "zero_spike_samples",
            "mean_output_spikes",
        ]
    ].agg(["mean", "std"])
)

                        best_test_accuracy           spike_accuracy            \
                                      mean       std           mean       std
output_threshold input
0.50             memory             0.4475  0.203562         0.4475  0.203562
                 raw                0.3050  0.122984         0.3050  0.122984
0.75             memory             0.4525  0.193730         0.4525  0.193730
                 raw                0.3025  0.117394         0.3025  0.117394
1.00             memory             0.4425  0.185321         0.4425  0.185321
                 raw                0.2975  0.106213         0.2975  0.106213

                        membrane_accuracy           zero_spike_samples  \
                                     mean       std               mean
output_threshold input
0.50             memory            0.4225  0.189860               42.4
                 raw               0.3100  0.134164               67.6
0.75             memory            0.4300  0.184687               44.0
                 raw               0.3050  0.122984               66.4
1.00             memory            0.4400  0.192719               49.2
                 raw               0.3025  0.117394               74.6

                                   mean_output_spikes
                               std               mean       std
output_threshold input
0.50             memory  35.934663             1.2600  1.351226
                 raw     27.727243             0.2725  0.609329
0.75             memory  33.815677             1.0825  1.050320
                 raw     30.410524             0.2825  0.631689
1.00             memory  30.638211             0.8900  0.935807
                 raw     12.074767             0.1375  0.307459

In [16]:
diagnostic_columns = [
    "seed",
    "input",
    "output_threshold",
    "best_test_accuracy",
    "spike_accuracy",
    "membrane_accuracy",
    "zero_spike_samples",
    "mean_output_spikes",
]

print("OUTPUT THRESHOLD = 0.50")
display(
    threshold_050_results["results"][diagnostic_columns]
    .sort_values(["seed", "input"])
    .reset_index(drop=True)
)

print("\nOUTPUT THRESHOLD = 0.75")
display(
    threshold_075_results["results"][diagnostic_columns]
    .sort_values(["seed", "input"])
    .reset_index(drop=True)
)

OUTPUT THRESHOLD = 0.50

,seed,input,output_threshold,best_test_accuracy,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,memory,0.5,0.2500,0.2500,0.2500,80,0.0000
1,0,raw,0.5,0.2500,0.2500,0.2500,80,0.0000
2,1,memory,0.5,0.4625,0.4625,0.3875,27,1.3000
3,1,raw,0.5,0.2500,0.2500,0.2500,80,0.0000
4,2,memory,0.5,0.7250,0.7250,0.6875,25,1.7750
5,2,raw,0.5,0.2500,0.2500,0.2500,80,0.0000
6,3,memory,0.5,0.2500,0.2500,0.2500,80,0.0000
7,3,raw,0.5,0.2500,0.2500,0.2500,80,0.0000
8,4,memory,0.5,0.5500,0.5500,0.5375,0,3.2250
9,4,raw,0.5,0.5250,0.5250,0.5500,18,1.3625

OUTPUT THRESHOLD = 0.75

,seed,input,output_threshold,best_test_accuracy,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,memory,0.75,0.2500,0.2500,0.2500,80,0.0000
1,0,raw,0.75,0.2500,0.2500,0.2500,80,0.0000
2,1,memory,0.75,0.5125,0.5125,0.4375,26,1.3375
3,1,raw,0.75,0.2500,0.2500,0.2500,80,0.0000
4,2,memory,0.75,0.6750,0.6750,0.6750,27,1.7375
5,2,raw,0.75,0.2500,0.2500,0.2500,80,0.0000
6,3,memory,0.75,0.2500,0.2500,0.2500,80,0.0000
7,3,raw,0.75,0.2500,0.2500,0.2500,80,0.0000
8,4,memory,0.75,0.5750,0.5750,0.5375,7,2.3375
9,4,raw,0.75,0.5125,0.5125,0.5250,12,1.4125

## Need to test upstream layers

In [17]:
@torch.no_grad()
def diagnose_layer_spiking(model, data_loader, device=device):
    """
    Measure where activity disappears inside the trained SNN.

    For each LIF layer:
      - mean total spikes per test sample across all timesteps
      - number of test samples with zero spikes across all timesteps
    """
    model.eval()

    layer_names = ["lif1", "lif2", "lif3", "lif_out"]

    # Stores per-sample total spike counts across the whole test set
    all_sample_counts = {name: [] for name in layer_names}

    # Temporary storage for one batch.
    # Each LIF module is called once per timestep.
    batch_counts = {name: [] for name in layer_names}

    hooks = []

    def make_hook(name):
        def hook(module, inputs, output):
            # snn.Leaky returns (spikes, membrane)
            spikes = output[0]

            # Sum over every dimension except batch.
            # Gives one spike count per sample for this timestep.
            per_sample = spikes.flatten(start_dim=1).sum(dim=1)

            batch_counts[name].append(per_sample.detach().cpu())

        return hook

    # Attach hooks
    for name in layer_names:
        layer = getattr(model, name)
        hooks.append(layer.register_forward_hook(make_hook(name)))

    for spike_movies, _ in data_loader:
        spike_movies = spike_movies.to(device)

        # Clear this batch's timestep records
        for name in layer_names:
            batch_counts[name] = []

        # Normal forward pass
        model(spike_movies)

        # Sum each sample's activity across all timesteps
        for name in layer_names:
            timestep_counts = torch.stack(batch_counts[name], dim=0)
            sample_totals = timestep_counts.sum(dim=0)
            all_sample_counts[name].append(sample_totals)

    # Remove hooks
    for hook in hooks:
        hook.remove()

    rows = []

    for name in layer_names:
        counts = torch.cat(all_sample_counts[name])

        rows.append({
            "layer": name,
            "mean_spikes_per_sample": counts.float().mean().item(),
            "zero_spike_samples": int((counts == 0).sum().item()),
            "zero_spike_fraction": float((counts == 0).float().mean().item()),
        })

    return pd.DataFrame(rows)

In [18]:
memory_seed2_050 = threshold_050_results["models"]["memory"][2]
memory_seed3_050 = threshold_050_results["models"]["memory"][3]

print("MEMORY — threshold 0.5 — seed 2 (successful)")
display(
    diagnose_layer_spiking(
        memory_seed2_050,
        memory_test_loader,
        device,
    )
)

print("MEMORY — threshold 0.5 — seed 3 (collapsed)")
display(
    diagnose_layer_spiking(
        memory_seed3_050,
        memory_test_loader,
        device,
    )
)

MEMORY — threshold 0.5 — seed 2 (successful)

     layer  mean_spikes_per_sample  zero_spike_samples  zero_spike_fraction
0     lif1             3186.399902                   0               0.0000
1     lif2               26.637501                   0               0.0000
2     lif3               20.687500                   8               0.1000
3  lif_out                1.775000                  25               0.3125

MEMORY — threshold 0.5 — seed 3 (collapsed)

     layer  mean_spikes_per_sample  zero_spike_samples  zero_spike_fraction
0     lif1               50.924999                   0                  0.0
1     lif2                0.000000                  80                  1.0
2     lif3                0.000000                  80                  1.0
3  lif_out                0.000000                  80                  1.0

SO activity dies much earlier in the bad seeds  - as early as LIF1. Will attempt to lower feature threshold

In [19]:
threshold_075_results = run_threshold_comparison(
    feature_threshold=0.75,
    output_threshold=0.75,
)

Seed 0 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7359 | train acc 0.344 | test acc 0.338
epoch 05 | loss 9.2566 | train acc 0.334 | test acc 0.312
epoch 06 | loss 8.9020 | train acc 0.488 | test acc 0.375
epoch 07 | loss 8.5821 | train acc 0.534 | test acc 0.287
epoch 08 | loss 8.2401 | train acc 0.609 | test acc 0.350
epoch 09 | loss 7.7827 | train acc 0.675 | test acc 0.375
epoch 10 | loss 7.3139 | train acc 0.788 | test acc 0.387
epoch 11 | loss 6.8011 | train acc 0.816 | test acc 0.400
epoch 12 | loss 6.2972 | train acc 0.884 | test acc 0.400
epoch 13 | loss 5.8258 | train acc 0.931 | test acc 0.412
epoch 14 | loss 5.3073 | train acc 0.956 | test acc 0.425
epoch 15 | loss 4.8491 | train acc 0.969 | test acc 0.400
epoch 16 | loss 4.4533 | train acc 0.991 | test acc 0.425
epoch 17 | loss 4.1264 | train acc 0.997 | test acc 0.412
epoch 18 | loss 3.8419 | train acc 1.000 | test acc 0.425
epoch 19 | loss 3.6430 | train acc 0.997 | test acc 0.412
epoch 20 | loss 3.4403 | train acc 1.000 | test acc 0.412
epoch 21 | loss 3.2815 | train acc 1.000 | test acc 0.412
epoch 22 | loss 3.1607 | train acc 0.997 | test acc 0.400
epoch 23 | loss 3.0735 | train acc 1.000 | test acc 0.387
epoch 24 | loss 2.9959 | train acc 1.000 | test acc 0.412
epoch 25 | loss 2.9392 | train acc 1.000 | test acc 0.400
epoch 26 | loss 2.8855 | train acc 1.000 | test acc 0.400
epoch 27 | loss 2.8337 | train acc 1.000 | test acc 0.400
epoch 28 | loss 2.7945 | train acc 1.000 | test acc 0.412
epoch 29 | loss 2.7594 | train acc 1.000 | test acc 0.400
epoch 30 | loss 2.7200 | train acc 1.000 | test acc 0.412
epoch 31 | loss 2.6924 | train acc 1.000 | test acc 0.400
epoch 32 | loss 2.6615 | train acc 1.000 | test acc 0.400
epoch 33 | loss 2.6345 | train acc 1.000 | test acc 0.412
epoch 34 | loss 2.6129 | train acc 1.000 | test acc 0.400
epoch 35 | loss 2.5858 | train acc 1.000 | test acc 0.400
epoch 36 | loss 2.5656 | train acc 1.000 | test acc 0.400
epoch 37 | loss 2.5389 | train acc 1.000 | test acc 0.375
epoch 38 | loss 2.5082 | train acc 1.000 | test acc 0.387
epoch 39 | loss 2.4813 | train acc 1.000 | test acc 0.387
epoch 40 | loss 2.4514 | train acc 1.000 | test acc 0.387
epoch 41 | loss 2.4162 | train acc 1.000 | test acc 0.400
epoch 42 | loss 2.3801 | train acc 1.000 | test acc 0.412
epoch 43 | loss 2.3454 | train acc 1.000 | test acc 0.400
epoch 44 | loss 2.3083 | train acc 1.000 | test acc 0.400
epoch 45 | loss 2.2679 | train acc 1.000 | test acc 0.400
epoch 46 | loss 2.2268 | train acc 1.000 | test acc 0.387
epoch 47 | loss 2.1906 | train acc 1.000 | test acc 0.400
epoch 48 | loss 2.1462 | train acc 1.000 | test acc 0.400
epoch 49 | loss 2.0993 | train acc 1.000 | test acc 0.400

Seed 1 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8219 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7295 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.5746 | train acc 0.463 | test acc 0.438
epoch 05 | loss 9.5234 | train acc 0.375 | test acc 0.338
epoch 06 | loss 9.0937 | train acc 0.400 | test acc 0.363
epoch 07 | loss 8.7406 | train acc 0.491 | test acc 0.450
epoch 08 | loss 8.4429 | train acc 0.450 | test acc 0.400
epoch 09 | loss 8.2062 | train acc 0.488 | test acc 0.475
epoch 10 | loss 8.0104 | train acc 0.491 | test acc 0.475
epoch 11 | loss 7.8397 | train acc 0.512 | test acc 0.475
epoch 12 | loss 7.6437 | train acc 0.538 | test acc 0.488
epoch 13 | loss 7.4467 | train acc 0.550 | test acc 0.475
epoch 14 | loss 7.2420 | train acc 0.600 | test acc 0.463
epoch 15 | loss 6.9888 | train acc 0.666 | test acc 0.475
epoch 16 | loss 6.7794 | train acc 0.700 | test acc 0.450
epoch 17 | loss 6.5297 | train acc 0.703 | test acc 0.475
epoch 18 | loss 6.3307 | train acc 0.772 | test acc 0.500
epoch 19 | loss 6.0696 | train acc 0.794 | test acc 0.500
epoch 20 | loss 5.8371 | train acc 0.788 | test acc 0.525
epoch 21 | loss 5.6649 | train acc 0.834 | test acc 0.550
epoch 22 | loss 5.4802 | train acc 0.828 | test acc 0.488
epoch 23 | loss 5.2936 | train acc 0.837 | test acc 0.512
epoch 24 | loss 5.1518 | train acc 0.834 | test acc 0.500
epoch 25 | loss 5.0103 | train acc 0.859 | test acc 0.525
epoch 26 | loss 4.8316 | train acc 0.884 | test acc 0.512
epoch 27 | loss 4.6250 | train acc 0.887 | test acc 0.525
epoch 28 | loss 4.4390 | train acc 0.919 | test acc 0.512
epoch 29 | loss 4.3024 | train acc 0.931 | test acc 0.538
epoch 30 | loss 4.1452 | train acc 0.922 | test acc 0.512
epoch 31 | loss 3.9680 | train acc 0.947 | test acc 0.550
epoch 32 | loss 3.8173 | train acc 0.944 | test acc 0.525
epoch 33 | loss 3.7316 | train acc 0.959 | test acc 0.512
epoch 34 | loss 3.5528 | train acc 0.969 | test acc 0.500
epoch 35 | loss 3.4562 | train acc 0.978 | test acc 0.512
epoch 36 | loss 3.3027 | train acc 0.984 | test acc 0.525
epoch 37 | loss 3.2073 | train acc 0.991 | test acc 0.525
epoch 38 | loss 3.1110 | train acc 0.984 | test acc 0.525
epoch 39 | loss 3.0230 | train acc 0.994 | test acc 0.500
epoch 40 | loss 2.9304 | train acc 0.991 | test acc 0.512
epoch 41 | loss 2.8612 | train acc 1.000 | test acc 0.550
epoch 42 | loss 2.8220 | train acc 1.000 | test acc 0.488
epoch 43 | loss 2.7280 | train acc 0.994 | test acc 0.512
epoch 44 | loss 2.6629 | train acc 0.997 | test acc 0.488
epoch 45 | loss 2.6477 | train acc 0.997 | test acc 0.550
epoch 46 | loss 2.5794 | train acc 0.997 | test acc 0.500
epoch 47 | loss 2.5302 | train acc 0.997 | test acc 0.512
epoch 48 | loss 2.4608 | train acc 1.000 | test acc 0.525
epoch 49 | loss 2.4292 | train acc 0.997 | test acc 0.525

Seed 1 | memory | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.4406 | train acc 0.253 | test acc 0.250
epoch 03 | loss 9.5204 | train acc 0.428 | test acc 0.425
epoch 04 | loss 8.9689 | train acc 0.509 | test acc 0.463
epoch 05 | loss 8.5940 | train acc 0.512 | test acc 0.375
epoch 06 | loss 8.2189 | train acc 0.650 | test acc 0.350
epoch 07 | loss 7.6769 | train acc 0.756 | test acc 0.438
epoch 08 | loss 6.8037 | train acc 0.806 | test acc 0.438
epoch 09 | loss 6.0514 | train acc 0.841 | test acc 0.400
epoch 10 | loss 5.5967 | train acc 0.900 | test acc 0.438
epoch 11 | loss 5.2101 | train acc 0.938 | test acc 0.412
epoch 12 | loss 4.8247 | train acc 0.950 | test acc 0.400
epoch 13 | loss 4.4666 | train acc 0.966 | test acc 0.412
epoch 14 | loss 4.1135 | train acc 0.988 | test acc 0.412
epoch 15 | loss 3.7996 | train acc 0.991 | test acc 0.400
epoch 16 | loss 3.5406 | train acc 0.994 | test acc 0.450
epoch 17 | loss 3.3112 | train acc 0.997 | test acc 0.438
epoch 18 | loss 3.1628 | train acc 1.000 | test acc 0.438
epoch 19 | loss 3.0168 | train acc 1.000 | test acc 0.463
epoch 20 | loss 2.9135 | train acc 1.000 | test acc 0.412
epoch 21 | loss 2.8325 | train acc 1.000 | test acc 0.375
epoch 22 | loss 2.7629 | train acc 1.000 | test acc 0.425
epoch 23 | loss 2.6831 | train acc 1.000 | test acc 0.387
epoch 24 | loss 2.6298 | train acc 1.000 | test acc 0.387
epoch 25 | loss 2.5767 | train acc 1.000 | test acc 0.438
epoch 26 | loss 2.5385 | train acc 1.000 | test acc 0.425
epoch 27 | loss 2.5024 | train acc 1.000 | test acc 0.425
epoch 28 | loss 2.4554 | train acc 1.000 | test acc 0.412
epoch 29 | loss 2.4239 | train acc 1.000 | test acc 0.400
epoch 30 | loss 2.3935 | train acc 1.000 | test acc 0.400
epoch 31 | loss 2.3682 | train acc 1.000 | test acc 0.375
epoch 32 | loss 2.3442 | train acc 1.000 | test acc 0.387
epoch 33 | loss 2.3177 | train acc 1.000 | test acc 0.387
epoch 34 | loss 2.2965 | train acc 1.000 | test acc 0.400
epoch 35 | loss 2.2751 | train acc 1.000 | test acc 0.400
epoch 36 | loss 2.2499 | train acc 1.000 | test acc 0.387
epoch 37 | loss 2.2267 | train acc 1.000 | test acc 0.387
epoch 38 | loss 2.2026 | train acc 1.000 | test acc 0.363
epoch 39 | loss 2.1807 | train acc 1.000 | test acc 0.350
epoch 40 | loss 2.1621 | train acc 1.000 | test acc 0.363
epoch 41 | loss 2.1415 | train acc 1.000 | test acc 0.387
epoch 42 | loss 2.1401 | train acc 1.000 | test acc 0.387
epoch 43 | loss 2.0948 | train acc 1.000 | test acc 0.425
epoch 44 | loss 2.0523 | train acc 1.000 | test acc 0.438
epoch 45 | loss 2.0111 | train acc 1.000 | test acc 0.400
epoch 46 | loss 1.9614 | train acc 1.000 | test acc 0.425
epoch 47 | loss 1.9189 | train acc 1.000 | test acc 0.412
epoch 48 | loss 1.8723 | train acc 1.000 | test acc 0.438
epoch 49 | loss 1.8274 | train acc 1.000 | test acc 0.400

Seed 2 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7646 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7307 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7335 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7148 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.6920 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.6750 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.5955 | train acc 0.431 | test acc 0.363
epoch 09 | loss 9.3277 | train acc 0.444 | test acc 0.387
epoch 10 | loss 9.0501 | train acc 0.478 | test acc 0.387
epoch 11 | loss 8.6846 | train acc 0.453 | test acc 0.400
epoch 12 | loss 8.3841 | train acc 0.475 | test acc 0.450
epoch 13 | loss 8.0690 | train acc 0.472 | test acc 0.475
epoch 14 | loss 7.7685 | train acc 0.503 | test acc 0.475
epoch 15 | loss 7.5773 | train acc 0.503 | test acc 0.475
epoch 16 | loss 7.3815 | train acc 0.534 | test acc 0.475
epoch 17 | loss 7.1375 | train acc 0.575 | test acc 0.500
epoch 18 | loss 6.8596 | train acc 0.619 | test acc 0.512
epoch 19 | loss 6.5898 | train acc 0.681 | test acc 0.512
epoch 20 | loss 6.3232 | train acc 0.697 | test acc 0.450
epoch 21 | loss 6.0398 | train acc 0.719 | test acc 0.438
epoch 22 | loss 5.9214 | train acc 0.744 | test acc 0.475
epoch 23 | loss 5.7236 | train acc 0.769 | test acc 0.475
epoch 24 | loss 5.4740 | train acc 0.819 | test acc 0.512
epoch 25 | loss 5.2737 | train acc 0.816 | test acc 0.463
epoch 26 | loss 5.1396 | train acc 0.859 | test acc 0.500
epoch 27 | loss 4.9510 | train acc 0.859 | test acc 0.475
epoch 28 | loss 4.7875 | train acc 0.875 | test acc 0.488
epoch 29 | loss 4.5926 | train acc 0.900 | test acc 0.488
epoch 30 | loss 4.4638 | train acc 0.900 | test acc 0.512
epoch 31 | loss 4.2697 | train acc 0.906 | test acc 0.512
epoch 32 | loss 4.1280 | train acc 0.928 | test acc 0.475
epoch 33 | loss 4.0465 | train acc 0.925 | test acc 0.463
epoch 34 | loss 3.9253 | train acc 0.947 | test acc 0.475
epoch 35 | loss 3.7699 | train acc 0.959 | test acc 0.512
epoch 36 | loss 3.6455 | train acc 0.956 | test acc 0.475
epoch 37 | loss 3.5288 | train acc 0.966 | test acc 0.463
epoch 38 | loss 3.3727 | train acc 0.969 | test acc 0.463
epoch 39 | loss 3.2923 | train acc 0.956 | test acc 0.475
epoch 40 | loss 3.3570 | train acc 0.962 | test acc 0.475
epoch 41 | loss 3.1767 | train acc 0.972 | test acc 0.450
epoch 42 | loss 3.0062 | train acc 0.978 | test acc 0.488
epoch 43 | loss 2.9057 | train acc 0.981 | test acc 0.463
epoch 44 | loss 2.8019 | train acc 0.984 | test acc 0.463
epoch 45 | loss 2.7205 | train acc 0.978 | test acc 0.488
epoch 46 | loss 2.6655 | train acc 0.981 | test acc 0.463
epoch 47 | loss 2.5943 | train acc 0.984 | test acc 0.475
epoch 48 | loss 2.5007 | train acc 0.988 | test acc 0.488
epoch 49 | loss 2.4513 | train acc 0.981 | test acc 0.500

Seed 2 | memory | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7484 | train acc 0.247 | test acc 0.250
epoch 02 | loss 9.7561 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.6545 | train acc 0.262 | test acc 0.250
epoch 04 | loss 9.5034 | train acc 0.319 | test acc 0.275
epoch 05 | loss 9.2988 | train acc 0.625 | test acc 0.400
epoch 06 | loss 8.5666 | train acc 0.616 | test acc 0.412
epoch 07 | loss 7.9812 | train acc 0.738 | test acc 0.538
epoch 08 | loss 7.4596 | train acc 0.803 | test acc 0.538
epoch 09 | loss 6.9820 | train acc 0.759 | test acc 0.538
epoch 10 | loss 6.6115 | train acc 0.856 | test acc 0.525
epoch 11 | loss 6.3109 | train acc 0.844 | test acc 0.512
epoch 12 | loss 6.0361 | train acc 0.881 | test acc 0.500
epoch 13 | loss 5.8305 | train acc 0.919 | test acc 0.500
epoch 14 | loss 5.5427 | train acc 0.941 | test acc 0.500
epoch 15 | loss 5.2731 | train acc 0.941 | test acc 0.525
epoch 16 | loss 4.9906 | train acc 0.959 | test acc 0.512
epoch 17 | loss 4.7521 | train acc 0.981 | test acc 0.488
epoch 18 | loss 4.4891 | train acc 0.984 | test acc 0.488
epoch 19 | loss 4.2130 | train acc 0.994 | test acc 0.500
epoch 20 | loss 3.9709 | train acc 0.997 | test acc 0.475
epoch 21 | loss 3.7346 | train acc 0.997 | test acc 0.500
epoch 22 | loss 3.5297 | train acc 1.000 | test acc 0.500
epoch 23 | loss 3.3414 | train acc 1.000 | test acc 0.500
epoch 24 | loss 3.1825 | train acc 1.000 | test acc 0.500
epoch 25 | loss 3.0597 | train acc 1.000 | test acc 0.500
epoch 26 | loss 2.9395 | train acc 1.000 | test acc 0.500
epoch 27 | loss 2.8484 | train acc 1.000 | test acc 0.500
epoch 28 | loss 2.7648 | train acc 1.000 | test acc 0.512
epoch 29 | loss 2.7122 | train acc 1.000 | test acc 0.500
epoch 30 | loss 2.6486 | train acc 1.000 | test acc 0.488
epoch 31 | loss 2.5980 | train acc 1.000 | test acc 0.500
epoch 32 | loss 2.5468 | train acc 1.000 | test acc 0.500
epoch 33 | loss 2.5078 | train acc 1.000 | test acc 0.463
epoch 34 | loss 2.4515 | train acc 1.000 | test acc 0.488
epoch 35 | loss 2.4715 | train acc 1.000 | test acc 0.500
epoch 36 | loss 2.3993 | train acc 1.000 | test acc 0.500
epoch 37 | loss 2.3790 | train acc 1.000 | test acc 0.525
epoch 38 | loss 2.3060 | train acc 1.000 | test acc 0.525
epoch 39 | loss 2.2562 | train acc 1.000 | test acc 0.500
epoch 40 | loss 2.2072 | train acc 1.000 | test acc 0.500
epoch 41 | loss 2.1635 | train acc 1.000 | test acc 0.525
epoch 42 | loss 2.1157 | train acc 1.000 | test acc 0.500
epoch 43 | loss 2.0718 | train acc 1.000 | test acc 0.488
epoch 44 | loss 2.0140 | train acc 1.000 | test acc 0.488
epoch 45 | loss 1.9635 | train acc 1.000 | test acc 0.488
epoch 46 | loss 1.9205 | train acc 1.000 | test acc 0.488
epoch 47 | loss 1.8782 | train acc 1.000 | test acc 0.475
epoch 48 | loss 1.8337 | train acc 1.000 | test acc 0.475
epoch 49 | loss 1.8048 | train acc 1.000 | test acc 0.475

Seed 3 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,0.75,0.75,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,0.75,0.75,0.4250,14,0.4250,0.4250,7,2.7625
2,1,raw,0.75,0.75,0.5500,21,0.5500,0.5125,11,2.2375
3,1,memory,0.75,0.75,0.4625,4,0.4625,0.4250,47,0.6750
4,2,raw,0.75,0.75,0.5125,18,0.5125,0.5500,34,1.4000
5,2,memory,0.75,0.75,0.5375,7,0.5375,0.5250,2,2.2875
6,3,raw,0.75,0.75,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,0.75,0.75,0.4125,6,0.4125,0.3750,21,1.3875
8,4,raw,0.75,0.75,0.5250,18,0.5250,0.5000,2,2.8750
9,4,memory,0.75,0.75,0.5250,11,0.5250,0.5250,0,3.6250

input  memory     raw  memory_minus_raw
seed
0      0.4250  0.2500            0.1750
1      0.4625  0.5500           -0.0875
2      0.5375  0.5125            0.0250
3      0.4125  0.2500            0.1625
4      0.5250  0.5250            0.0000

                    mean
input
memory            0.4725
raw               0.4175
memory_minus_raw  0.0550

In [21]:
threshold_050_results = run_threshold_comparison(
    feature_threshold=0.75,
    output_threshold=0.5,
)

Seed 0 | raw | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7355 | train acc 0.369 | test acc 0.338
epoch 05 | loss 9.2477 | train acc 0.344 | test acc 0.300
epoch 06 | loss 8.9055 | train acc 0.528 | test acc 0.375
epoch 07 | loss 8.5983 | train acc 0.547 | test acc 0.312
epoch 08 | loss 8.2316 | train acc 0.678 | test acc 0.350
epoch 09 | loss 7.7726 | train acc 0.731 | test acc 0.375
epoch 10 | loss 7.2769 | train acc 0.794 | test acc 0.400
epoch 11 | loss 6.7449 | train acc 0.850 | test acc 0.400
epoch 12 | loss 6.2148 | train acc 0.891 | test acc 0.387
epoch 13 | loss 5.7035 | train acc 0.931 | test acc 0.387
epoch 14 | loss 5.1896 | train acc 0.953 | test acc 0.425
epoch 15 | loss 4.7414 | train acc 0.981 | test acc 0.425
epoch 16 | loss 4.3251 | train acc 0.984 | test acc 0.425
epoch 17 | loss 4.0104 | train acc 0.994 | test acc 0.412
epoch 18 | loss 3.7578 | train acc 1.000 | test acc 0.412
epoch 19 | loss 3.5774 | train acc 1.000 | test acc 0.425
epoch 20 | loss 3.4043 | train acc 1.000 | test acc 0.425
epoch 21 | loss 3.2549 | train acc 1.000 | test acc 0.425
epoch 22 | loss 3.1196 | train acc 1.000 | test acc 0.412
epoch 23 | loss 3.0229 | train acc 1.000 | test acc 0.412
epoch 24 | loss 2.9515 | train acc 1.000 | test acc 0.412
epoch 25 | loss 2.8923 | train acc 1.000 | test acc 0.412
epoch 26 | loss 2.8491 | train acc 1.000 | test acc 0.387
epoch 27 | loss 2.8104 | train acc 1.000 | test acc 0.425
epoch 28 | loss 2.7690 | train acc 1.000 | test acc 0.425
epoch 29 | loss 2.7401 | train acc 1.000 | test acc 0.412
epoch 30 | loss 2.7088 | train acc 1.000 | test acc 0.412
epoch 31 | loss 2.6783 | train acc 1.000 | test acc 0.412
epoch 32 | loss 2.6526 | train acc 1.000 | test acc 0.412
epoch 33 | loss 2.6204 | train acc 1.000 | test acc 0.412
epoch 34 | loss 2.5930 | train acc 1.000 | test acc 0.412
epoch 35 | loss 2.5644 | train acc 1.000 | test acc 0.400
epoch 36 | loss 2.5370 | train acc 1.000 | test acc 0.387
epoch 37 | loss 2.5117 | train acc 1.000 | test acc 0.387
epoch 38 | loss 2.4782 | train acc 1.000 | test acc 0.387
epoch 39 | loss 2.4414 | train acc 1.000 | test acc 0.400
epoch 40 | loss 2.4160 | train acc 1.000 | test acc 0.412
epoch 41 | loss 2.3837 | train acc 1.000 | test acc 0.387
epoch 42 | loss 2.3476 | train acc 1.000 | test acc 0.400
epoch 43 | loss 2.3090 | train acc 1.000 | test acc 0.400
epoch 44 | loss 2.2646 | train acc 1.000 | test acc 0.375
epoch 45 | loss 2.2202 | train acc 1.000 | test acc 0.387
epoch 46 | loss 2.1804 | train acc 1.000 | test acc 0.387
epoch 47 | loss 2.1404 | train acc 1.000 | test acc 0.387
epoch 48 | loss 2.1052 | train acc 1.000 | test acc 0.412
epoch 49 | loss 2.0687 | train acc 1.000 | test acc 0.400

Seed 1 | raw | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8385 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7470 | train acc 0.262 | test acc 0.250
epoch 04 | loss 9.6860 | train acc 0.494 | test acc 0.463
epoch 05 | loss 9.5973 | train acc 0.331 | test acc 0.312
epoch 06 | loss 9.0793 | train acc 0.325 | test acc 0.312
epoch 07 | loss 8.7210 | train acc 0.509 | test acc 0.463
epoch 08 | loss 8.4574 | train acc 0.447 | test acc 0.375
epoch 09 | loss 8.2197 | train acc 0.522 | test acc 0.438
epoch 10 | loss 8.0343 | train acc 0.528 | test acc 0.450
epoch 11 | loss 7.8520 | train acc 0.591 | test acc 0.450
epoch 12 | loss 7.6328 | train acc 0.625 | test acc 0.463
epoch 13 | loss 7.4078 | train acc 0.669 | test acc 0.488
epoch 14 | loss 7.1143 | train acc 0.697 | test acc 0.488
epoch 15 | loss 6.7840 | train acc 0.647 | test acc 0.475
epoch 16 | loss 6.4116 | train acc 0.672 | test acc 0.488
epoch 17 | loss 6.1561 | train acc 0.663 | test acc 0.450
epoch 18 | loss 6.0254 | train acc 0.700 | test acc 0.438
epoch 19 | loss 5.7258 | train acc 0.753 | test acc 0.475
epoch 20 | loss 5.5277 | train acc 0.769 | test acc 0.425
epoch 21 | loss 5.3795 | train acc 0.831 | test acc 0.488
epoch 22 | loss 5.2254 | train acc 0.844 | test acc 0.488
epoch 23 | loss 5.0911 | train acc 0.809 | test acc 0.512
epoch 24 | loss 5.0487 | train acc 0.850 | test acc 0.475
epoch 25 | loss 4.8416 | train acc 0.850 | test acc 0.500
epoch 26 | loss 4.6538 | train acc 0.900 | test acc 0.488
epoch 27 | loss 4.4894 | train acc 0.884 | test acc 0.463
epoch 28 | loss 4.3558 | train acc 0.897 | test acc 0.488
epoch 29 | loss 4.2473 | train acc 0.909 | test acc 0.475
epoch 30 | loss 4.0517 | train acc 0.931 | test acc 0.450
epoch 31 | loss 3.9216 | train acc 0.947 | test acc 0.500
epoch 32 | loss 3.7994 | train acc 0.944 | test acc 0.488
epoch 33 | loss 3.6760 | train acc 0.947 | test acc 0.512
epoch 34 | loss 3.5646 | train acc 0.956 | test acc 0.525
epoch 35 | loss 3.4696 | train acc 0.966 | test acc 0.512
epoch 36 | loss 3.3685 | train acc 0.975 | test acc 0.525
epoch 37 | loss 3.2676 | train acc 0.975 | test acc 0.538
epoch 38 | loss 3.1847 | train acc 0.978 | test acc 0.550
epoch 39 | loss 3.0903 | train acc 0.981 | test acc 0.538
epoch 40 | loss 3.0030 | train acc 0.991 | test acc 0.538
epoch 41 | loss 2.9480 | train acc 0.991 | test acc 0.550
epoch 42 | loss 2.8728 | train acc 0.991 | test acc 0.538
epoch 43 | loss 2.7991 | train acc 0.991 | test acc 0.512
epoch 44 | loss 2.7568 | train acc 1.000 | test acc 0.512
epoch 45 | loss 2.6985 | train acc 1.000 | test acc 0.525
epoch 46 | loss 2.6599 | train acc 1.000 | test acc 0.512
epoch 47 | loss 2.6062 | train acc 1.000 | test acc 0.525
epoch 48 | loss 2.5868 | train acc 1.000 | test acc 0.512
epoch 49 | loss 2.5513 | train acc 1.000 | test acc 0.500

Seed 1 | memory | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.4107 | train acc 0.269 | test acc 0.275
epoch 03 | loss 9.6106 | train acc 0.478 | test acc 0.412
epoch 04 | loss 8.9616 | train acc 0.500 | test acc 0.400
epoch 05 | loss 8.5587 | train acc 0.559 | test acc 0.312
epoch 06 | loss 8.1704 | train acc 0.697 | test acc 0.425
epoch 07 | loss 7.4927 | train acc 0.816 | test acc 0.412
epoch 08 | loss 6.5684 | train acc 0.822 | test acc 0.425
epoch 09 | loss 5.9458 | train acc 0.853 | test acc 0.438
epoch 10 | loss 5.5161 | train acc 0.919 | test acc 0.412
epoch 11 | loss 5.1187 | train acc 0.947 | test acc 0.400
epoch 12 | loss 4.7411 | train acc 0.962 | test acc 0.438
epoch 13 | loss 4.3304 | train acc 0.981 | test acc 0.412
epoch 14 | loss 4.0405 | train acc 0.991 | test acc 0.400
epoch 15 | loss 3.6966 | train acc 0.997 | test acc 0.438
epoch 16 | loss 3.4441 | train acc 1.000 | test acc 0.438
epoch 17 | loss 3.2377 | train acc 1.000 | test acc 0.450
epoch 18 | loss 3.0942 | train acc 1.000 | test acc 0.450
epoch 19 | loss 2.9701 | train acc 1.000 | test acc 0.412
epoch 20 | loss 2.8911 | train acc 1.000 | test acc 0.412
epoch 21 | loss 2.8007 | train acc 1.000 | test acc 0.425
epoch 22 | loss 2.7357 | train acc 1.000 | test acc 0.412
epoch 23 | loss 2.6732 | train acc 1.000 | test acc 0.412
epoch 24 | loss 2.6265 | train acc 1.000 | test acc 0.400
epoch 25 | loss 2.5844 | train acc 1.000 | test acc 0.412
epoch 26 | loss 2.5531 | train acc 1.000 | test acc 0.412
epoch 27 | loss 2.5179 | train acc 1.000 | test acc 0.387
epoch 28 | loss 2.4837 | train acc 1.000 | test acc 0.425
epoch 29 | loss 2.4596 | train acc 1.000 | test acc 0.400
epoch 30 | loss 2.4324 | train acc 1.000 | test acc 0.400
epoch 31 | loss 2.4031 | train acc 1.000 | test acc 0.412
epoch 32 | loss 2.3773 | train acc 1.000 | test acc 0.400
epoch 33 | loss 2.3499 | train acc 1.000 | test acc 0.400
epoch 34 | loss 2.3298 | train acc 1.000 | test acc 0.387
epoch 35 | loss 2.2957 | train acc 1.000 | test acc 0.375
epoch 36 | loss 2.2752 | train acc 1.000 | test acc 0.438
epoch 37 | loss 2.2362 | train acc 1.000 | test acc 0.412
epoch 38 | loss 2.2006 | train acc 1.000 | test acc 0.400
epoch 39 | loss 2.1633 | train acc 1.000 | test acc 0.412
epoch 40 | loss 2.1319 | train acc 1.000 | test acc 0.438
epoch 41 | loss 2.1046 | train acc 1.000 | test acc 0.425
epoch 42 | loss 2.0737 | train acc 1.000 | test acc 0.412
epoch 43 | loss 2.0447 | train acc 1.000 | test acc 0.438
epoch 44 | loss 2.0125 | train acc 1.000 | test acc 0.450
epoch 45 | loss 1.9779 | train acc 1.000 | test acc 0.425
epoch 46 | loss 1.9409 | train acc 1.000 | test acc 0.438
epoch 47 | loss 1.8970 | train acc 1.000 | test acc 0.412
epoch 48 | loss 1.8514 | train acc 1.000 | test acc 0.412
epoch 49 | loss 1.8045 | train acc 1.000 | test acc 0.400

Seed 2 | raw | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7646 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7307 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7335 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7148 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.6920 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.6750 | train acc 0.278 | test acc 0.275
epoch 08 | loss 9.5955 | train acc 0.444 | test acc 0.375
epoch 09 | loss 9.3232 | train acc 0.400 | test acc 0.350
epoch 10 | loss 9.0260 | train acc 0.472 | test acc 0.400
epoch 11 | loss 8.6607 | train acc 0.441 | test acc 0.400
epoch 12 | loss 8.3509 | train acc 0.472 | test acc 0.412
epoch 13 | loss 8.0520 | train acc 0.472 | test acc 0.450
epoch 14 | loss 7.7659 | train acc 0.516 | test acc 0.475
epoch 15 | loss 7.5558 | train acc 0.531 | test acc 0.500
epoch 16 | loss 7.3422 | train acc 0.616 | test acc 0.525
epoch 17 | loss 7.0967 | train acc 0.644 | test acc 0.450
epoch 18 | loss 6.8455 | train acc 0.700 | test acc 0.500
epoch 19 | loss 6.5488 | train acc 0.725 | test acc 0.463
epoch 20 | loss 6.2785 | train acc 0.762 | test acc 0.488
epoch 21 | loss 6.0246 | train acc 0.781 | test acc 0.475
epoch 22 | loss 5.9052 | train acc 0.791 | test acc 0.500
epoch 23 | loss 5.6759 | train acc 0.841 | test acc 0.500
epoch 24 | loss 5.5346 | train acc 0.819 | test acc 0.538
epoch 25 | loss 5.3381 | train acc 0.831 | test acc 0.525
epoch 26 | loss 5.1010 | train acc 0.875 | test acc 0.512
epoch 27 | loss 4.9324 | train acc 0.878 | test acc 0.488
epoch 28 | loss 4.7772 | train acc 0.884 | test acc 0.525
epoch 29 | loss 4.6072 | train acc 0.894 | test acc 0.500
epoch 30 | loss 4.4167 | train acc 0.913 | test acc 0.500
epoch 31 | loss 4.2608 | train acc 0.938 | test acc 0.488
epoch 32 | loss 4.1096 | train acc 0.934 | test acc 0.488
epoch 33 | loss 4.0084 | train acc 0.956 | test acc 0.500
epoch 34 | loss 3.8225 | train acc 0.959 | test acc 0.512
epoch 35 | loss 3.7601 | train acc 0.959 | test acc 0.525
epoch 36 | loss 3.5913 | train acc 0.953 | test acc 0.525
epoch 37 | loss 3.5267 | train acc 0.969 | test acc 0.488
epoch 38 | loss 3.3740 | train acc 0.966 | test acc 0.525
epoch 39 | loss 3.2076 | train acc 0.978 | test acc 0.525
epoch 40 | loss 3.1674 | train acc 0.969 | test acc 0.512
epoch 41 | loss 3.0410 | train acc 0.984 | test acc 0.538
epoch 42 | loss 2.8978 | train acc 0.981 | test acc 0.500
epoch 43 | loss 2.8286 | train acc 0.988 | test acc 0.525
epoch 44 | loss 2.7625 | train acc 0.984 | test acc 0.512
epoch 45 | loss 2.6935 | train acc 0.991 | test acc 0.525
epoch 46 | loss 2.6446 | train acc 0.988 | test acc 0.488
epoch 47 | loss 2.5617 | train acc 0.988 | test acc 0.512
epoch 48 | loss 2.4790 | train acc 0.991 | test acc 0.475
epoch 49 | loss 2.4537 | train acc 0.988 | test acc 0.463

Seed 2 | memory | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7484 | train acc 0.316 | test acc 0.275
epoch 02 | loss 9.7561 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.6545 | train acc 0.447 | test acc 0.363
epoch 04 | loss 9.5034 | train acc 0.406 | test acc 0.325
epoch 05 | loss 9.3527 | train acc 0.609 | test acc 0.400
epoch 06 | loss 8.6317 | train acc 0.647 | test acc 0.475
epoch 07 | loss 7.9364 | train acc 0.756 | test acc 0.512
epoch 08 | loss 7.3160 | train acc 0.800 | test acc 0.512
epoch 09 | loss 6.8767 | train acc 0.819 | test acc 0.525
epoch 10 | loss 6.5117 | train acc 0.853 | test acc 0.525
epoch 11 | loss 6.2421 | train acc 0.878 | test acc 0.512
epoch 12 | loss 5.9779 | train acc 0.906 | test acc 0.512
epoch 13 | loss 5.6893 | train acc 0.934 | test acc 0.512
epoch 14 | loss 5.4098 | train acc 0.944 | test acc 0.512
epoch 15 | loss 5.0957 | train acc 0.962 | test acc 0.500
epoch 16 | loss 4.7802 | train acc 0.969 | test acc 0.500
epoch 17 | loss 4.4925 | train acc 0.988 | test acc 0.500
epoch 18 | loss 4.1904 | train acc 0.984 | test acc 0.475
epoch 19 | loss 3.9291 | train acc 0.994 | test acc 0.512
epoch 20 | loss 3.6752 | train acc 0.997 | test acc 0.488
epoch 21 | loss 3.4493 | train acc 0.997 | test acc 0.500
epoch 22 | loss 3.2606 | train acc 1.000 | test acc 0.500
epoch 23 | loss 3.1287 | train acc 1.000 | test acc 0.512
epoch 24 | loss 3.0103 | train acc 1.000 | test acc 0.512
epoch 25 | loss 2.9089 | train acc 1.000 | test acc 0.512
epoch 26 | loss 2.8353 | train acc 1.000 | test acc 0.512
epoch 27 | loss 2.8247 | train acc 1.000 | test acc 0.500
epoch 28 | loss 2.7203 | train acc 1.000 | test acc 0.488
epoch 29 | loss 2.6603 | train acc 1.000 | test acc 0.512
epoch 30 | loss 2.5924 | train acc 1.000 | test acc 0.525
epoch 31 | loss 2.5463 | train acc 1.000 | test acc 0.525
epoch 32 | loss 2.5017 | train acc 1.000 | test acc 0.525
epoch 33 | loss 2.4668 | train acc 1.000 | test acc 0.525
epoch 34 | loss 2.4332 | train acc 1.000 | test acc 0.500
epoch 35 | loss 2.4021 | train acc 1.000 | test acc 0.512
epoch 36 | loss 2.3717 | train acc 1.000 | test acc 0.512
epoch 37 | loss 2.3326 | train acc 1.000 | test acc 0.512
epoch 38 | loss 2.2953 | train acc 1.000 | test acc 0.500
epoch 39 | loss 2.2478 | train acc 1.000 | test acc 0.500
epoch 40 | loss 2.1895 | train acc 1.000 | test acc 0.475
epoch 41 | loss 2.1252 | train acc 1.000 | test acc 0.488
epoch 42 | loss 2.0734 | train acc 1.000 | test acc 0.500
epoch 43 | loss 2.0166 | train acc 1.000 | test acc 0.463
epoch 44 | loss 1.9710 | train acc 1.000 | test acc 0.500
epoch 45 | loss 1.9139 | train acc 1.000 | test acc 0.488
epoch 46 | loss 1.8634 | train acc 1.000 | test acc 0.500
epoch 47 | loss 1.8176 | train acc 1.000 | test acc 0.500
epoch 48 | loss 1.7684 | train acc 1.000 | test acc 0.500
epoch 49 | loss 1.7354 | train acc 1.000 | test acc 0.500

Seed 3 | raw | feature threshold=0.75 | output threshold=0.5
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,0.75,0.5,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,0.75,0.5,0.4250,14,0.4250,0.4500,2,3.7000
2,1,raw,0.75,0.5,0.5500,38,0.5500,0.4875,4,2.8625
3,1,memory,0.75,0.5,0.4500,17,0.4500,0.4250,1,4.1875
4,2,raw,0.75,0.5,0.5375,24,0.5375,0.5125,4,3.2875
5,2,memory,0.75,0.5,0.5250,9,0.5250,0.5500,0,3.9625
6,3,raw,0.75,0.5,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,0.75,0.5,0.4125,6,0.4125,0.3625,11,2.1875
8,4,raw,0.75,0.5,0.5750,16,0.5750,0.5000,0,4.9125
9,4,memory,0.75,0.5,0.5250,8,0.5250,0.4875,0,3.5000

input  memory     raw  memory_minus_raw
seed
0      0.4250  0.2500            0.1750
1      0.4500  0.5500           -0.1000
2      0.5250  0.5375           -0.0125
3      0.4125  0.2500            0.1625
4      0.5250  0.5750           -0.0500

                    mean
input
memory            0.4675
raw               0.4325
memory_minus_raw  0.0350

In [22]:
threshold_075_results = run_threshold_comparison(
    feature_threshold=0.85,
    output_threshold=0.5,
)

Seed 0 | raw | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7350 | train acc 0.269 | test acc 0.262
epoch 09 | loss 9.4916 | train acc 0.353 | test acc 0.312
epoch 10 | loss 9.2811 | train acc 0.409 | test acc 0.387
epoch 11 | loss 9.0865 | train acc 0.391 | test acc 0.363
epoch 12 | loss 8.9520 | train acc 0.428 | test acc 0.400
epoch 13 | loss 8.7935 | train acc 0.431 | test acc 0.375
epoch 14 | loss 8.6107 | train acc 0.503 | test acc 0.363
epoch 15 | loss 8.4539 | train acc 0.587 | test acc 0.412
epoch 16 | loss 8.2759 | train acc 0.666 | test acc 0.400
epoch 17 | loss 8.1084 | train acc 0.681 | test acc 0.425
epoch 18 | loss 7.8915 | train acc 0.753 | test acc 0.400
epoch 19 | loss 7.6472 | train acc 0.769 | test acc 0.412
epoch 20 | loss 7.3773 | train acc 0.803 | test acc 0.350
epoch 21 | loss 7.1081 | train acc 0.816 | test acc 0.387
epoch 22 | loss 6.8496 | train acc 0.853 | test acc 0.412
epoch 23 | loss 6.5422 | train acc 0.872 | test acc 0.412
epoch 24 | loss 6.3138 | train acc 0.906 | test acc 0.400
epoch 25 | loss 5.9452 | train acc 0.922 | test acc 0.438
epoch 26 | loss 5.6654 | train acc 0.928 | test acc 0.412
epoch 27 | loss 5.4223 | train acc 0.947 | test acc 0.400
epoch 28 | loss 5.1880 | train acc 0.959 | test acc 0.400
epoch 29 | loss 4.9459 | train acc 0.972 | test acc 0.425
epoch 30 | loss 4.7326 | train acc 0.984 | test acc 0.412
epoch 31 | loss 4.5262 | train acc 0.981 | test acc 0.400
epoch 32 | loss 4.3679 | train acc 0.988 | test acc 0.438
epoch 33 | loss 4.2292 | train acc 0.994 | test acc 0.387
epoch 34 | loss 4.0879 | train acc 0.997 | test acc 0.425
epoch 35 | loss 3.9722 | train acc 0.997 | test acc 0.387
epoch 36 | loss 3.8587 | train acc 0.994 | test acc 0.387
epoch 37 | loss 3.7350 | train acc 1.000 | test acc 0.412
epoch 38 | loss 3.6232 | train acc 1.000 | test acc 0.412
epoch 39 | loss 3.5259 | train acc 1.000 | test acc 0.387
epoch 40 | loss 3.4266 | train acc 1.000 | test acc 0.375
epoch 41 | loss 3.3134 | train acc 1.000 | test acc 0.375
epoch 42 | loss 3.2285 | train acc 1.000 | test acc 0.363
epoch 43 | loss 3.1778 | train acc 1.000 | test acc 0.375
epoch 44 | loss 3.1354 | train acc 1.000 | test acc 0.350
epoch 45 | loss 3.1105 | train acc 1.000 | test acc 0.350
epoch 46 | loss 3.0499 | train acc 1.000 | test acc 0.363
epoch 47 | loss 2.9956 | train acc 0.997 | test acc 0.363
epoch 48 | loss 2.9546 | train acc 0.997 | test acc 0.350
epoch 49 | loss 2.9079 | train acc 0.997 | test acc 0.338

Seed 1 | raw | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8019 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7488 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7325 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7158 | train acc 0.316 | test acc 0.262
epoch 07 | loss 9.6519 | train acc 0.384 | test acc 0.350
epoch 08 | loss 9.5453 | train acc 0.484 | test acc 0.450
epoch 09 | loss 9.3413 | train acc 0.500 | test acc 0.463
epoch 10 | loss 9.0299 | train acc 0.497 | test acc 0.463
epoch 11 | loss 8.5421 | train acc 0.519 | test acc 0.438
epoch 12 | loss 8.1275 | train acc 0.575 | test acc 0.450
epoch 13 | loss 7.8399 | train acc 0.597 | test acc 0.463
epoch 14 | loss 7.6082 | train acc 0.591 | test acc 0.488
epoch 15 | loss 7.4407 | train acc 0.634 | test acc 0.500
epoch 16 | loss 7.2916 | train acc 0.641 | test acc 0.500
epoch 17 | loss 7.1809 | train acc 0.650 | test acc 0.538
epoch 18 | loss 7.0981 | train acc 0.684 | test acc 0.550
epoch 19 | loss 7.0114 | train acc 0.706 | test acc 0.512
epoch 20 | loss 6.9113 | train acc 0.722 | test acc 0.562
epoch 21 | loss 6.7981 | train acc 0.728 | test acc 0.500
epoch 22 | loss 6.6848 | train acc 0.719 | test acc 0.475
epoch 23 | loss 6.5689 | train acc 0.750 | test acc 0.512
epoch 24 | loss 6.4819 | train acc 0.759 | test acc 0.488
epoch 25 | loss 6.3884 | train acc 0.766 | test acc 0.500
epoch 26 | loss 6.3016 | train acc 0.775 | test acc 0.500
epoch 27 | loss 6.1773 | train acc 0.788 | test acc 0.512
epoch 28 | loss 6.0745 | train acc 0.797 | test acc 0.512
epoch 29 | loss 5.9496 | train acc 0.781 | test acc 0.550
epoch 30 | loss 5.9525 | train acc 0.784 | test acc 0.550
epoch 31 | loss 5.8839 | train acc 0.809 | test acc 0.525
epoch 32 | loss 5.7582 | train acc 0.831 | test acc 0.525
epoch 33 | loss 5.6435 | train acc 0.853 | test acc 0.550
epoch 34 | loss 5.5230 | train acc 0.847 | test acc 0.525
epoch 35 | loss 5.4423 | train acc 0.863 | test acc 0.550
epoch 36 | loss 5.3012 | train acc 0.875 | test acc 0.538
epoch 37 | loss 5.2324 | train acc 0.853 | test acc 0.538
epoch 38 | loss 5.1329 | train acc 0.869 | test acc 0.562
epoch 39 | loss 4.9345 | train acc 0.881 | test acc 0.562
epoch 40 | loss 4.8532 | train acc 0.887 | test acc 0.587
epoch 41 | loss 4.7441 | train acc 0.897 | test acc 0.575
epoch 42 | loss 4.5859 | train acc 0.897 | test acc 0.538
epoch 43 | loss 4.4541 | train acc 0.894 | test acc 0.538
epoch 44 | loss 4.3622 | train acc 0.922 | test acc 0.550
epoch 45 | loss 4.2179 | train acc 0.928 | test acc 0.562
epoch 46 | loss 4.1351 | train acc 0.925 | test acc 0.575
epoch 47 | loss 4.0418 | train acc 0.928 | test acc 0.550
epoch 48 | loss 3.9561 | train acc 0.925 | test acc 0.575
epoch 49 | loss 3.9480 | train acc 0.941 | test acc 0.562

Seed 1 | memory | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7695 | train acc 0.453 | test acc 0.425
epoch 03 | loss 9.4802 | train acc 0.469 | test acc 0.425
epoch 04 | loss 9.2795 | train acc 0.303 | test acc 0.275
epoch 05 | loss 9.3001 | train acc 0.606 | test acc 0.463
epoch 06 | loss 8.8227 | train acc 0.684 | test acc 0.525
epoch 07 | loss 8.2121 | train acc 0.716 | test acc 0.500
epoch 08 | loss 7.6199 | train acc 0.769 | test acc 0.525
epoch 09 | loss 7.2085 | train acc 0.772 | test acc 0.500
epoch 10 | loss 6.9427 | train acc 0.828 | test acc 0.500
epoch 11 | loss 6.6909 | train acc 0.863 | test acc 0.475
epoch 12 | loss 6.3680 | train acc 0.872 | test acc 0.475
epoch 13 | loss 6.0701 | train acc 0.906 | test acc 0.438
epoch 14 | loss 5.7743 | train acc 0.922 | test acc 0.450
epoch 15 | loss 5.4915 | train acc 0.953 | test acc 0.450
epoch 16 | loss 5.1726 | train acc 0.953 | test acc 0.412
epoch 17 | loss 4.8613 | train acc 0.978 | test acc 0.425
epoch 18 | loss 4.5968 | train acc 0.991 | test acc 0.387
epoch 19 | loss 4.3283 | train acc 0.994 | test acc 0.387
epoch 20 | loss 4.0989 | train acc 0.994 | test acc 0.412
epoch 21 | loss 3.9089 | train acc 0.997 | test acc 0.375
epoch 22 | loss 3.7448 | train acc 0.997 | test acc 0.425
epoch 23 | loss 3.6118 | train acc 0.997 | test acc 0.387
epoch 24 | loss 3.4926 | train acc 1.000 | test acc 0.438
epoch 25 | loss 3.3646 | train acc 1.000 | test acc 0.438
epoch 26 | loss 3.2625 | train acc 1.000 | test acc 0.425
epoch 27 | loss 3.1629 | train acc 1.000 | test acc 0.412
epoch 28 | loss 3.0822 | train acc 1.000 | test acc 0.425
epoch 29 | loss 3.0111 | train acc 1.000 | test acc 0.425
epoch 30 | loss 2.9539 | train acc 1.000 | test acc 0.438
epoch 31 | loss 2.8995 | train acc 1.000 | test acc 0.438
epoch 32 | loss 2.8473 | train acc 1.000 | test acc 0.438
epoch 33 | loss 2.8028 | train acc 1.000 | test acc 0.450
epoch 34 | loss 2.7596 | train acc 1.000 | test acc 0.425
epoch 35 | loss 2.7263 | train acc 1.000 | test acc 0.425
epoch 36 | loss 2.6891 | train acc 1.000 | test acc 0.412
epoch 37 | loss 2.6537 | train acc 1.000 | test acc 0.412
epoch 38 | loss 2.6339 | train acc 0.997 | test acc 0.412
epoch 39 | loss 2.6558 | train acc 1.000 | test acc 0.412
epoch 40 | loss 2.5816 | train acc 1.000 | test acc 0.425
epoch 41 | loss 2.5159 | train acc 1.000 | test acc 0.412
epoch 42 | loss 2.4668 | train acc 1.000 | test acc 0.425
epoch 43 | loss 2.4258 | train acc 1.000 | test acc 0.425
epoch 44 | loss 2.3940 | train acc 1.000 | test acc 0.425
epoch 45 | loss 2.3582 | train acc 1.000 | test acc 0.425
epoch 46 | loss 2.3191 | train acc 1.000 | test acc 0.412
epoch 47 | loss 2.2871 | train acc 1.000 | test acc 0.412
epoch 48 | loss 2.2499 | train acc 1.000 | test acc 0.425
epoch 49 | loss 2.2212 | train acc 1.000 | test acc 0.425

Seed 2 | raw | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7683 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7479 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7264 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7336 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7310 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7334 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7074 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.6857 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7512 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.6949 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.6783 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.6575 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.6276 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.6087 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.5425 | train acc 0.269 | test acc 0.262
epoch 20 | loss 9.4419 | train acc 0.334 | test acc 0.287
epoch 21 | loss 9.3469 | train acc 0.378 | test acc 0.375
epoch 22 | loss 9.2451 | train acc 0.450 | test acc 0.425
epoch 23 | loss 9.1292 | train acc 0.481 | test acc 0.412
epoch 24 | loss 8.9657 | train acc 0.478 | test acc 0.438
epoch 25 | loss 8.7646 | train acc 0.484 | test acc 0.463
epoch 26 | loss 8.5507 | train acc 0.497 | test acc 0.463
epoch 27 | loss 8.3206 | train acc 0.478 | test acc 0.438
epoch 28 | loss 8.1489 | train acc 0.500 | test acc 0.475
epoch 29 | loss 8.0065 | train acc 0.494 | test acc 0.475
epoch 30 | loss 7.8706 | train acc 0.500 | test acc 0.463
epoch 31 | loss 7.7681 | train acc 0.503 | test acc 0.488
epoch 32 | loss 7.6725 | train acc 0.500 | test acc 0.488
epoch 33 | loss 7.5717 | train acc 0.512 | test acc 0.475
epoch 34 | loss 7.5046 | train acc 0.522 | test acc 0.488
epoch 35 | loss 7.4642 | train acc 0.525 | test acc 0.500
epoch 36 | loss 7.3586 | train acc 0.528 | test acc 0.500
epoch 37 | loss 7.2468 | train acc 0.522 | test acc 0.488
epoch 38 | loss 7.1537 | train acc 0.547 | test acc 0.488
epoch 39 | loss 7.0738 | train acc 0.578 | test acc 0.550
epoch 40 | loss 6.9814 | train acc 0.559 | test acc 0.525
epoch 41 | loss 6.9205 | train acc 0.606 | test acc 0.550
epoch 42 | loss 6.8447 | train acc 0.613 | test acc 0.525
epoch 43 | loss 6.8160 | train acc 0.625 | test acc 0.550
epoch 44 | loss 6.7668 | train acc 0.647 | test acc 0.562
epoch 45 | loss 6.7241 | train acc 0.641 | test acc 0.575
epoch 46 | loss 6.6310 | train acc 0.644 | test acc 0.587
epoch 47 | loss 6.5311 | train acc 0.650 | test acc 0.550
epoch 48 | loss 6.4958 | train acc 0.681 | test acc 0.575
epoch 49 | loss 6.4307 | train acc 0.684 | test acc 0.550

Seed 2 | memory | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.6828 | train acc 0.284 | test acc 0.225
epoch 04 | loss 9.6989 | train acc 0.369 | test acc 0.275
epoch 05 | loss 9.5763 | train acc 0.422 | test acc 0.325
epoch 06 | loss 9.4134 | train acc 0.444 | test acc 0.338
epoch 07 | loss 8.9731 | train acc 0.541 | test acc 0.412
epoch 08 | loss 8.5874 | train acc 0.663 | test acc 0.463
epoch 09 | loss 8.2162 | train acc 0.678 | test acc 0.463
epoch 10 | loss 7.9105 | train acc 0.725 | test acc 0.463
epoch 11 | loss 7.7134 | train acc 0.750 | test acc 0.538
epoch 12 | loss 7.6533 | train acc 0.784 | test acc 0.538
epoch 13 | loss 7.1643 | train acc 0.397 | test acc 0.300
epoch 14 | loss 7.3796 | train acc 0.834 | test acc 0.562
epoch 15 | loss 6.7027 | train acc 0.837 | test acc 0.550
epoch 16 | loss 6.4823 | train acc 0.875 | test acc 0.538
epoch 17 | loss 6.2577 | train acc 0.891 | test acc 0.525
epoch 18 | loss 6.0023 | train acc 0.900 | test acc 0.550
epoch 19 | loss 5.9794 | train acc 0.944 | test acc 0.575
epoch 20 | loss 5.6592 | train acc 0.934 | test acc 0.525
epoch 21 | loss 5.4785 | train acc 0.959 | test acc 0.500
epoch 22 | loss 5.2881 | train acc 0.975 | test acc 0.500
epoch 23 | loss 5.1394 | train acc 0.984 | test acc 0.475
epoch 24 | loss 4.9574 | train acc 0.984 | test acc 0.488
epoch 25 | loss 4.8086 | train acc 0.994 | test acc 0.463
epoch 26 | loss 4.6906 | train acc 0.991 | test acc 0.500
epoch 27 | loss 4.5619 | train acc 0.997 | test acc 0.463
epoch 28 | loss 4.4565 | train acc 0.991 | test acc 0.475
epoch 29 | loss 4.3393 | train acc 0.994 | test acc 0.488
epoch 30 | loss 4.2396 | train acc 0.994 | test acc 0.488
epoch 31 | loss 4.1666 | train acc 0.994 | test acc 0.475
epoch 32 | loss 4.0722 | train acc 0.997 | test acc 0.463
epoch 33 | loss 3.9752 | train acc 1.000 | test acc 0.475
epoch 34 | loss 3.8738 | train acc 1.000 | test acc 0.475
epoch 35 | loss 3.7862 | train acc 1.000 | test acc 0.475
epoch 36 | loss 3.6941 | train acc 1.000 | test acc 0.475
epoch 37 | loss 3.6258 | train acc 1.000 | test acc 0.463
epoch 38 | loss 3.5466 | train acc 1.000 | test acc 0.463
epoch 39 | loss 3.4698 | train acc 1.000 | test acc 0.463
epoch 40 | loss 3.4049 | train acc 1.000 | test acc 0.488
epoch 41 | loss 3.3388 | train acc 1.000 | test acc 0.488
epoch 42 | loss 3.2865 | train acc 1.000 | test acc 0.488
epoch 43 | loss 3.2323 | train acc 1.000 | test acc 0.475
epoch 44 | loss 3.1787 | train acc 1.000 | test acc 0.488
epoch 45 | loss 3.1238 | train acc 1.000 | test acc 0.488
epoch 46 | loss 3.1886 | train acc 1.000 | test acc 0.438
epoch 47 | loss 3.1335 | train acc 1.000 | test acc 0.450
epoch 48 | loss 2.9952 | train acc 1.000 | test acc 0.475
epoch 49 | loss 2.8739 | train acc 1.000 | test acc 0.475

Seed 3 | raw | feature threshold=0.85 | output threshold=0.5
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,0.85,0.5,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,0.85,0.5,0.4375,25,0.4375,0.4375,2,2.9875
2,1,raw,0.85,0.5,0.5875,40,0.5875,0.6125,0,5.1000
3,1,memory,0.85,0.5,0.5250,6,0.5250,0.3750,9,1.6750
4,2,raw,0.85,0.5,0.5875,46,0.5875,0.5750,11,1.8875
5,2,memory,0.85,0.5,0.5750,19,0.5750,0.5625,0,3.6000
6,3,raw,0.85,0.5,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,0.85,0.5,0.4500,9,0.4500,0.3875,22,1.5500
8,4,raw,0.85,0.5,0.5750,10,0.5750,0.5000,0,3.5625
9,4,memory,0.85,0.5,0.5500,10,0.5500,0.5375,0,3.1500

input  memory     raw  memory_minus_raw
seed
0      0.4375  0.2500            0.1875
1      0.5250  0.5875           -0.0625
2      0.5750  0.5875           -0.0125
3      0.4500  0.2500            0.2000
4      0.5500  0.5750           -0.0250

                    mean
input
memory            0.5075
raw               0.4500
memory_minus_raw  0.0575

In [24]:
threshold_075_results = run_threshold_comparison(
    feature_threshold=0.9,
    output_threshold=0.5,
)

Seed 0 | raw | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 1 | raw | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8329 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.8119 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7861 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7703 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7642 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7603 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7548 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7623 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7466 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7283 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7004 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.6750 | train acc 0.378 | test acc 0.363
epoch 14 | loss 9.6213 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.6278 | train acc 0.253 | test acc 0.250
epoch 16 | loss 9.4699 | train acc 0.444 | test acc 0.425
epoch 17 | loss 9.3300 | train acc 0.466 | test acc 0.438
epoch 18 | loss 9.1266 | train acc 0.488 | test acc 0.463
epoch 19 | loss 8.9120 | train acc 0.466 | test acc 0.463
epoch 20 | loss 8.6664 | train acc 0.500 | test acc 0.488
epoch 21 | loss 8.4771 | train acc 0.494 | test acc 0.488
epoch 22 | loss 8.3015 | train acc 0.497 | test acc 0.488
epoch 23 | loss 8.1778 | train acc 0.500 | test acc 0.488
epoch 24 | loss 8.1073 | train acc 0.494 | test acc 0.500
epoch 25 | loss 7.9558 | train acc 0.500 | test acc 0.500
epoch 26 | loss 7.8980 | train acc 0.497 | test acc 0.500
epoch 27 | loss 7.8229 | train acc 0.500 | test acc 0.500
epoch 28 | loss 7.7548 | train acc 0.500 | test acc 0.500
epoch 29 | loss 7.7130 | train acc 0.500 | test acc 0.500
epoch 30 | loss 7.6661 | train acc 0.500 | test acc 0.500
epoch 31 | loss 7.6328 | train acc 0.500 | test acc 0.488
epoch 32 | loss 7.5912 | train acc 0.500 | test acc 0.488
epoch 33 | loss 7.5521 | train acc 0.500 | test acc 0.488
epoch 34 | loss 7.5277 | train acc 0.500 | test acc 0.500
epoch 35 | loss 7.5009 | train acc 0.500 | test acc 0.500
epoch 36 | loss 7.4653 | train acc 0.506 | test acc 0.500
epoch 37 | loss 7.4311 | train acc 0.538 | test acc 0.500
epoch 38 | loss 7.4002 | train acc 0.562 | test acc 0.500
epoch 39 | loss 7.3741 | train acc 0.566 | test acc 0.500
epoch 40 | loss 7.3686 | train acc 0.584 | test acc 0.512
epoch 41 | loss 7.3504 | train acc 0.584 | test acc 0.525
epoch 42 | loss 7.3410 | train acc 0.597 | test acc 0.550
epoch 43 | loss 7.2995 | train acc 0.619 | test acc 0.575
epoch 44 | loss 7.2710 | train acc 0.613 | test acc 0.525
epoch 45 | loss 7.2249 | train acc 0.609 | test acc 0.562
epoch 46 | loss 7.1817 | train acc 0.609 | test acc 0.550
epoch 47 | loss 7.1414 | train acc 0.613 | test acc 0.575
epoch 48 | loss 7.0966 | train acc 0.647 | test acc 0.538
epoch 49 | loss 7.0327 | train acc 0.656 | test acc 0.600

Seed 1 | memory | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7955 | train acc 0.428 | test acc 0.375
epoch 03 | loss 9.5539 | train acc 0.438 | test acc 0.400
epoch 04 | loss 9.3685 | train acc 0.491 | test acc 0.425
epoch 05 | loss 9.5378 | train acc 0.441 | test acc 0.387
epoch 06 | loss 9.1674 | train acc 0.544 | test acc 0.475
epoch 07 | loss 8.8515 | train acc 0.553 | test acc 0.475
epoch 08 | loss 8.3769 | train acc 0.691 | test acc 0.500
epoch 09 | loss 7.7308 | train acc 0.703 | test acc 0.488
epoch 10 | loss 7.3174 | train acc 0.753 | test acc 0.488
epoch 11 | loss 7.0190 | train acc 0.747 | test acc 0.450
epoch 12 | loss 6.7477 | train acc 0.822 | test acc 0.438
epoch 13 | loss 6.4706 | train acc 0.866 | test acc 0.425
epoch 14 | loss 6.1483 | train acc 0.859 | test acc 0.425
epoch 15 | loss 5.9127 | train acc 0.916 | test acc 0.375
epoch 16 | loss 5.6958 | train acc 0.928 | test acc 0.375
epoch 17 | loss 5.3972 | train acc 0.950 | test acc 0.400
epoch 18 | loss 5.1342 | train acc 0.959 | test acc 0.412
epoch 19 | loss 4.8787 | train acc 0.972 | test acc 0.400
epoch 20 | loss 4.6606 | train acc 0.988 | test acc 0.387
epoch 21 | loss 4.4478 | train acc 0.994 | test acc 0.412
epoch 22 | loss 4.2801 | train acc 0.997 | test acc 0.400
epoch 23 | loss 4.1197 | train acc 0.997 | test acc 0.412
epoch 24 | loss 3.9681 | train acc 0.997 | test acc 0.412
epoch 25 | loss 3.8825 | train acc 0.997 | test acc 0.375
epoch 26 | loss 3.7619 | train acc 0.997 | test acc 0.375
epoch 27 | loss 3.6448 | train acc 1.000 | test acc 0.412
epoch 28 | loss 3.5207 | train acc 1.000 | test acc 0.387
epoch 29 | loss 3.4458 | train acc 1.000 | test acc 0.400
epoch 30 | loss 3.3493 | train acc 1.000 | test acc 0.412
epoch 31 | loss 3.2765 | train acc 1.000 | test acc 0.400
epoch 32 | loss 3.2030 | train acc 1.000 | test acc 0.400
epoch 33 | loss 3.1371 | train acc 1.000 | test acc 0.400
epoch 34 | loss 3.0863 | train acc 1.000 | test acc 0.412
epoch 35 | loss 3.0283 | train acc 1.000 | test acc 0.412
epoch 36 | loss 2.9796 | train acc 1.000 | test acc 0.387
epoch 37 | loss 2.9458 | train acc 1.000 | test acc 0.400
epoch 38 | loss 2.9076 | train acc 1.000 | test acc 0.400
epoch 39 | loss 2.8678 | train acc 1.000 | test acc 0.412
epoch 40 | loss 2.8329 | train acc 1.000 | test acc 0.400
epoch 41 | loss 2.7953 | train acc 1.000 | test acc 0.425
epoch 42 | loss 2.7656 | train acc 1.000 | test acc 0.425
epoch 43 | loss 2.7369 | train acc 1.000 | test acc 0.425
epoch 44 | loss 2.7059 | train acc 1.000 | test acc 0.425
epoch 45 | loss 2.6844 | train acc 1.000 | test acc 0.425
epoch 46 | loss 2.6592 | train acc 1.000 | test acc 0.438
epoch 47 | loss 2.6378 | train acc 1.000 | test acc 0.412
epoch 48 | loss 2.6109 | train acc 1.000 | test acc 0.412
epoch 49 | loss 2.5854 | train acc 1.000 | test acc 0.412

Seed 2 | raw | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7506 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7443 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7405 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7366 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7315 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7282 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7258 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7234 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7216 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7190 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7177 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7158 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7143 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7131 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7124 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7113 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7100 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7087 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7070 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7064 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7052 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7044 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7051 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7050 | train acc 0.250 | test acc 0.250

Seed 2 | memory | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7543 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7516 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7368 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.6619 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7382 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7336 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.6699 | train acc 0.425 | test acc 0.325
epoch 08 | loss 9.3968 | train acc 0.444 | test acc 0.412
epoch 09 | loss 9.2803 | train acc 0.481 | test acc 0.425
epoch 10 | loss 8.8023 | train acc 0.531 | test acc 0.438
epoch 11 | loss 8.3927 | train acc 0.594 | test acc 0.475
epoch 12 | loss 8.0513 | train acc 0.594 | test acc 0.500
epoch 13 | loss 7.7802 | train acc 0.603 | test acc 0.425
epoch 14 | loss 7.5892 | train acc 0.706 | test acc 0.512
epoch 15 | loss 7.3996 | train acc 0.647 | test acc 0.475
epoch 16 | loss 7.4374 | train acc 0.750 | test acc 0.512
epoch 17 | loss 7.2378 | train acc 0.678 | test acc 0.488
epoch 18 | loss 7.0849 | train acc 0.759 | test acc 0.538
epoch 19 | loss 6.9250 | train acc 0.731 | test acc 0.500
epoch 20 | loss 6.7936 | train acc 0.788 | test acc 0.500
epoch 21 | loss 6.6482 | train acc 0.825 | test acc 0.525
epoch 22 | loss 6.6003 | train acc 0.803 | test acc 0.525
epoch 23 | loss 6.4179 | train acc 0.853 | test acc 0.512
epoch 24 | loss 6.2418 | train acc 0.866 | test acc 0.488
epoch 25 | loss 6.0592 | train acc 0.884 | test acc 0.512
epoch 26 | loss 5.8834 | train acc 0.903 | test acc 0.475
epoch 27 | loss 5.7157 | train acc 0.913 | test acc 0.512
epoch 28 | loss 5.5614 | train acc 0.919 | test acc 0.488
epoch 29 | loss 5.4129 | train acc 0.934 | test acc 0.500
epoch 30 | loss 5.2629 | train acc 0.953 | test acc 0.500
epoch 31 | loss 5.1214 | train acc 0.956 | test acc 0.500
epoch 32 | loss 4.9858 | train acc 0.966 | test acc 0.512
epoch 33 | loss 4.8652 | train acc 0.966 | test acc 0.500
epoch 34 | loss 4.7414 | train acc 0.966 | test acc 0.512
epoch 35 | loss 4.6368 | train acc 0.969 | test acc 0.512
epoch 36 | loss 4.5066 | train acc 0.978 | test acc 0.525
epoch 37 | loss 4.4235 | train acc 0.988 | test acc 0.525
epoch 38 | loss 4.2944 | train acc 0.984 | test acc 0.512
epoch 39 | loss 4.2167 | train acc 0.994 | test acc 0.512
epoch 40 | loss 4.1242 | train acc 0.991 | test acc 0.500
epoch 41 | loss 4.0238 | train acc 0.981 | test acc 0.500
epoch 42 | loss 3.9968 | train acc 0.991 | test acc 0.500
epoch 43 | loss 3.8992 | train acc 0.991 | test acc 0.500
epoch 44 | loss 3.7987 | train acc 0.994 | test acc 0.512
epoch 45 | loss 3.7248 | train acc 1.000 | test acc 0.500
epoch 46 | loss 3.6552 | train acc 1.000 | test acc 0.500
epoch 47 | loss 3.5720 | train acc 1.000 | test acc 0.512
epoch 48 | loss 3.5144 | train acc 1.000 | test acc 0.488
epoch 49 | loss 3.4450 | train acc 1.000 | test acc 0.438

Seed 3 | raw | feature threshold=0.9 | output threshold=0.5
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,0.9,0.5,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,0.9,0.5,0.2500,0,0.2500,0.2500,80,0.0000
2,1,raw,0.9,0.5,0.6000,49,0.6000,0.5875,2,2.0000
3,1,memory,0.9,0.5,0.5000,8,0.5000,0.4875,9,1.9750
4,2,raw,0.9,0.5,0.2500,0,0.2500,0.2500,80,0.0000
5,2,memory,0.9,0.5,0.5375,18,0.5375,0.5750,6,2.6625
6,3,raw,0.9,0.5,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,0.9,0.5,0.4750,13,0.4750,0.4250,15,1.7000
8,4,raw,0.9,0.5,0.5500,22,0.5500,0.4750,0,4.1125
9,4,memory,0.9,0.5,0.5500,15,0.5500,0.5250,0,3.9125

input  memory   raw  memory_minus_raw
seed
0      0.2500  0.25            0.0000
1      0.5000  0.60           -0.1000
2      0.5375  0.25            0.2875
3      0.4750  0.25            0.2250
4      0.5500  0.55            0.0000

                    mean
input
memory            0.4625
raw               0.3800
memory_minus_raw  0.0825

In [27]:
def quantify_velocity_estimation_on_classifier_dataset(
    raw_spikes_dataset,
    samples_per_shape=100,
    base_seed=0,
    max_speed=3,
    max_velocity=3,
    velocity_params=GOOD_VELOCITY_PARAMS,
):
    rows = []

    sample_index = 0

    for shape_name in SHAPE_NAMES:
        for _ in range(samples_per_shape):

            # Re-create the EXACT velocity sequence used when this sample
            # was originally generated.
            true_velocity_sequence = sample_random_velocity_sequence(
                num_transitions=STEPS - 1,
                max_speed=max_speed,
                allow_stationary=False,
                seed=base_seed + sample_index,
            )

            movie = raw_spikes_dataset[sample_index]

            for transition_index, (true_dy, true_dx) in enumerate(
                true_velocity_sequence
            ):
                previous_t = transition_index
                current_t = transition_index + 1

                result = (
                    lu.estimate_velocity_with_explicit_motion_pairs_and_inhibition(
                        previous_spikes=movie[previous_t],
                        current_spikes=movie[current_t],
                        max_offset=max_velocity,
                        **velocity_params,
                    )
                )

                estimated_dy = result["estimated_dy"]
                estimated_dx = result["estimated_dx"]

                # This is the gate ACTUALLY used by the current
                # displacement/ObjectMemory pipeline:
                # all velocity neurons that spiked at least once.
                velocity_gate = lu.get_velocity_gate_from_result(
                    result,
                    use_total_spikes=True,
                )

                true_i = true_dy + max_velocity
                true_j = true_dx + max_velocity

                true_velocity_in_gate = bool(
                    velocity_gate[true_i, true_j].item() > 0
                )

                num_active_velocity_gates = int(
                    velocity_gate.sum().item()
                )

                rows.append({
                    "sample": sample_index,
                    "shape": shape_name,
                    "transition": f"{previous_t}->{current_t}",

                    "true_dy": true_dy,
                    "true_dx": true_dx,

                    "estimated_dy": estimated_dy,
                    "estimated_dx": estimated_dx,

                    "winner_correct": (
                        estimated_dy == true_dy
                        and estimated_dx == true_dx
                    ),

                    "correct_dy": estimated_dy == true_dy,
                    "correct_dx": estimated_dx == true_dx,

                    "true_velocity_in_gate": true_velocity_in_gate,
                    "num_active_velocity_gates": num_active_velocity_gates,

                    # Useful measure of how "slow" the motion is.
                    # 1 means at least one component has magnitude 1, etc.
                    "max_component_speed": max(
                        abs(true_dy),
                        abs(true_dx),
                    ),

                    "euclidean_speed": (
                        true_dy**2 + true_dx**2
                    ) ** 0.5,
                })

            sample_index += 1

            if sample_index % 50 == 0:
                print(f"Processed {sample_index}/400 movies")

    return pd.DataFrame(rows)


velocity_dataset_results = quantify_velocity_estimation_on_classifier_dataset(
    raw_spikes_dataset
)

print("Total transitions:", len(velocity_dataset_results))
display(velocity_dataset_results.head())

Processed 50/400 movies
Processed 100/400 movies
Processed 150/400 movies
Processed 200/400 movies
Processed 250/400 movies
Processed 300/400 movies
Processed 350/400 movies
Processed 400/400 movies
Total transitions: 2400

,sample,shape,transition,true_dy,true_dx,estimated_dy,estimated_dx,winner_correct,correct_dy,correct_dx,true_velocity_in_gate,num_active_velocity_gates,max_component_speed,euclidean_speed
0,0,seven,0->1,1,0,1,0,True,True,True,True,1,1,1.000000
1,0,seven,1->2,-3,-1,-3,-1,True,True,True,True,1,3,3.162278
2,0,seven,2->3,-2,-1,-2,-1,True,True,True,True,1,2,2.236068
3,0,seven,3->4,3,0,3,0,True,True,True,True,1,3,3.000000
4,0,seven,4->5,1,2,1,2,True,True,True,True,1,2,2.236068

In [28]:
print("OVERALL")
display(pd.Series({
    "total_transitions": len(velocity_dataset_results),
    "winner_accuracy": velocity_dataset_results["winner_correct"].mean(),
    "true_velocity_in_gate_rate": velocity_dataset_results["true_velocity_in_gate"].mean(),
    "mean_active_velocity_gates": velocity_dataset_results["num_active_velocity_gates"].mean(),
}))

print("\nBY MAX COMPONENT SPEED")
display(
    velocity_dataset_results
    .groupby("max_component_speed")
    .agg(
        transitions=("winner_correct", "size"),
        winner_accuracy=("winner_correct", "mean"),
        true_velocity_in_gate_rate=("true_velocity_in_gate", "mean"),
        mean_active_velocity_gates=("num_active_velocity_gates", "mean"),
    )
)

print("\nBY SHAPE")
display(
    velocity_dataset_results
    .groupby("shape")
    .agg(
        transitions=("winner_correct", "size"),
        winner_accuracy=("winner_correct", "mean"),
        true_velocity_in_gate_rate=("true_velocity_in_gate", "mean"),
        mean_active_velocity_gates=("num_active_velocity_gates", "mean"),
    )
)

OVERALL

total_transitions             2400.000000
winner_accuracy                  1.000000
true_velocity_in_gate_rate       1.000000
mean_active_velocity_gates       2.999167
dtype: float64

BY MAX COMPONENT SPEED

,transitions,winner_accuracy,true_velocity_in_gate_rate,mean_active_velocity_gates
max_component_speed,,,,
1,387,1.0,1.0,3.413437
2,811,1.0,1.0,3.102343
3,1202,1.0,1.0,2.796173

BY SHAPE

,transitions,winner_accuracy,true_velocity_in_gate_rate,mean_active_velocity_gates
shape,,,,
box,600,1.0,1.0,8.996667
ell,600,1.0,1.0,1.000000
seven,600,1.0,1.0,1.000000
tee,600,1.0,1.0,1.000000

## Would like to pivot into less overlap motion modes to test memory vs raw inputs

In [29]:
def sample_fast_velocity_sequence(
    num_transitions,
    min_component_speed=4,
    max_speed=6,
    seed=None,
):
    """
    Sample velocity vectors with sufficiently large motion.

    Requirement:
        max(|dy|, |dx|) >= min_component_speed

    so every transition moves substantially in at least one axis.
    """
    if seed is not None:
        torch.manual_seed(seed)

    velocities = []

    for _ in range(num_transitions):
        while True:
            dy = int(
                torch.randint(
                    -max_speed,
                    max_speed + 1,
                    (1,),
                ).item()
            )
            dx = int(
                torch.randint(
                    -max_speed,
                    max_speed + 1,
                    (1,),
                ).item()
            )

            if max(abs(dy), abs(dx)) >= min_component_speed:
                break

        velocities.append((dy, dx))

    return velocities

In [30]:
def make_one_fast_classifier_dataset_sample(
    shape_name,
    min_component_speed=4,
    max_speed=6,
    sample_seed=0,
    max_velocity=6,
    max_displacement=36,
    velocity_params=None,
):
    if velocity_params is None:
        velocity_params = GOOD_VELOCITY_PARAMS

    velocity_sequence = sample_fast_velocity_sequence(
        STEPS - 1,
        min_component_speed=min_component_speed,
        max_speed=max_speed,
        seed=sample_seed,
    )

    start_top, start_left = (
        choose_safe_start_position_for_velocity_sequence(
            shape_name,
            velocity_sequence,
            seed=sample_seed + 10_000,
        )
    )

    case = lu.make_variable_velocity_spike_case(
        velocity_sequence=velocity_sequence,
        shape_name=shape_name,
        start_top=start_top,
        start_left=start_left,
    )

    memory_result = lu.run_displacement_gated_object_memory(
        case=case,
        max_velocity=max_velocity,
        max_displacement=max_displacement,
        velocity_params=velocity_params,
        threshold_memory=1.5,
        beta_memory=0.8,
        reset_mode="subtract",
    )

    return {
        "raw_spikes": case["spikes"].float(),
        "object_memory_spikes":
            memory_result["memory_spike_history"].float(),
        "label": SHAPE_TO_LABEL[shape_name],

        # Save these now so diagnostics are much easier.
        "velocity_sequence": velocity_sequence,
        "start_top": start_top,
        "start_left": start_left,
    }

In [31]:
def build_fast_classifier_dataset(
    samples_per_shape=100,
    min_component_speed=4,
    max_speed=6,
    max_velocity=6,
    max_displacement=36,
    base_seed=0,
):
    raw_samples = []
    memory_samples = []
    labels = []
    velocity_sequences = []

    total = samples_per_shape * len(SHAPE_NAMES)
    sample_index = 0

    for shape_name in SHAPE_NAMES:
        shape_count = 0

        while shape_count < samples_per_shape:
            seed = base_seed + sample_index

            try:
                sample = make_one_fast_classifier_dataset_sample(
                    shape_name=shape_name,
                    min_component_speed=min_component_speed,
                    max_speed=max_speed,
                    sample_seed=seed,
                    max_velocity=max_velocity,
                    max_displacement=max_displacement,
                )

            except ValueError:
                # Trajectory could not fit safely on 64x64.
                # Try a new random sequence.
                sample_index += 1
                continue

            raw_samples.append(sample["raw_spikes"])
            memory_samples.append(
                sample["object_memory_spikes"]
            )
            labels.append(sample["label"])
            velocity_sequences.append(
                sample["velocity_sequence"]
            )

            shape_count += 1
            sample_index += 1

            if len(labels) % 25 == 0:
                print(
                    f"Generated {len(labels)}/{total} samples"
                )

    return {
        "raw_spikes_dataset":
            torch.stack(raw_samples),

        "object_memory_spikes_dataset":
            torch.stack(memory_samples),

        "labels":
            torch.tensor(labels, dtype=torch.long),

        "velocity_sequences":
            velocity_sequences,
    }

In [32]:
fast_classifier_dataset = build_fast_classifier_dataset(
    samples_per_shape=100,
    min_component_speed=4,
    max_speed=6,
    max_velocity=6,
    max_displacement=36,
    base_seed=0,
)

fast_raw_spikes_dataset = (
    fast_classifier_dataset["raw_spikes_dataset"]
)

fast_memory_spikes_dataset = (
    fast_classifier_dataset["object_memory_spikes_dataset"]
)

fast_labels = fast_classifier_dataset["labels"]

fast_velocity_sequences = (
    fast_classifier_dataset["velocity_sequences"]
)

print("Raw:", fast_raw_spikes_dataset.shape)
print("Memory:", fast_memory_spikes_dataset.shape)
print("Labels:", fast_labels.shape)
print("Class counts:", torch.bincount(fast_labels))

Generated 25/400 samples
Generated 50/400 samples
Generated 75/400 samples
Generated 100/400 samples
Generated 125/400 samples
Generated 150/400 samples
Generated 175/400 samples
Generated 200/400 samples
Generated 225/400 samples
Generated 250/400 samples
Generated 275/400 samples
Generated 300/400 samples
Generated 325/400 samples
Generated 350/400 samples
Generated 375/400 samples
Generated 400/400 samples
Raw: torch.Size([400, 7, 64, 64])
Memory: torch.Size([400, 7, 64, 64])
Labels: torch.Size([400])
Class counts: tensor([100, 100, 100, 100])

In [33]:
def mean_consecutive_jaccard(movie_dataset):
    values = []

    for movie in movie_dataset:
        movie = movie > 0

        for t in range(movie.shape[0] - 1):
            a = movie[t]
            b = movie[t + 1]

            intersection = (a & b).sum().item()
            union = (a | b).sum().item()

            if union > 0:
                values.append(intersection / union)

    return sum(values) / len(values)


print(
    "Mean RAW consecutive overlap:",
    mean_consecutive_jaccard(
        fast_raw_spikes_dataset
    )
)

print(
    "Mean MEMORY consecutive overlap:",
    mean_consecutive_jaccard(
        fast_memory_spikes_dataset
    )
)

Mean RAW consecutive overlap: 0.011965234769390785
Mean MEMORY consecutive overlap: 1.0

In [38]:
fast_train_indices, fast_test_indices = make_stratified_train_test_split(
    fast_labels,
    seed=0,
)

fast_raw_train_loader, fast_raw_test_loader = make_dataloaders(
    fast_raw_spikes_dataset,
    fast_labels,
    fast_train_indices,
    fast_test_indices,
)

fast_memory_train_loader, fast_memory_test_loader = make_dataloaders(
    fast_memory_spikes_dataset,
    fast_labels,
    fast_train_indices,
    fast_test_indices,
)

print("Train samples:", len(fast_train_indices))
print("Test samples:", len(fast_test_indices))
print(
    "Test class counts:",
    torch.bincount(fast_labels[fast_test_indices]).tolist()
)

Train samples: 320
Test samples: 80
Test class counts: [20, 20, 20, 20]

In [39]:
FAST_SEEDS = [0, 1, 2, 3, 4]
FAST_NUM_EPOCHS = 50


def run_fast_threshold_comparison(
    output_threshold,
    feature_threshold=0.75,
):
    rows = []

    models = {
        "raw": {},
        "memory": {},
    }

    histories = {
        "raw": {},
        "memory": {},
    }

    for seed in FAST_SEEDS:

        for input_name, train_loader, test_loader in [

            (
                "raw",
                fast_raw_train_loader,
                fast_raw_test_loader,
            ),

            (
                "memory",
                fast_memory_train_loader,
                fast_memory_test_loader,
            ),

        ]:

            print(
                f"\nSeed {seed} | {input_name} | "
                f"feature threshold={feature_threshold} | "
                f"output threshold={output_threshold}"
            )

            set_all_seeds(seed)

            model, history = train_conv_spiking_classifier(
                train_loader=train_loader,
                test_loader=test_loader,
                num_classes=4,
                image_height=64,
                image_width=64,
                num_epochs=FAST_NUM_EPOCHS,
                learning_rate=5e-4,
                beta=0.95,
                feature_threshold=feature_threshold,
                output_threshold=output_threshold,
                device=device,
            )

            diagnostic = evaluate_classifier(
                model,
                test_loader,
                device=device,
            )

            models[input_name][seed] = model
            histories[input_name][seed] = history

            rows.append({
                "seed": seed,
                "input": input_name,

                "feature_threshold":
                    feature_threshold,

                "output_threshold":
                    output_threshold,

                "best_test_accuracy":
                    history["test_accuracy"].max(),

                "best_epoch":
                    int(
                        history["test_accuracy"].idxmax()
                    ),

                **diagnostic,
            })

    results = pd.DataFrame(rows)

    comparison = results.pivot(
        index="seed",
        columns="input",
        values="best_test_accuracy",
    )

    comparison["memory_minus_raw"] = (
        comparison["memory"]
        - comparison["raw"]
    )

    print("\nFULL RESULTS")
    display(results)

    print("\nMEMORY VS RAW BY SEED")
    display(comparison)

    print("\nMEAN RESULTS")
    display(
        comparison.mean().to_frame("mean")
    )

    return {
        "results": results,
        "comparison": comparison,
        "models": models,
        "histories": histories,
    }

In [40]:
fast_results = run_fast_threshold_comparison(
    feature_threshold=0.75,
    output_threshold=0.75,
)

Seed 0 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7814 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7720 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7566 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7491 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7431 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7384 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7339 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7305 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7285 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7242 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7170 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7156 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7142 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7130 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7116 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7103 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7096 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7092 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7083 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7077 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7076 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7072 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7066 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7069 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7059 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7056 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7061 | train acc 0.250 | test acc 0.250
epoch 37 | loss 9.7049 | train acc 0.250 | test acc 0.250
epoch 38 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 39 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 40 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 41 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 42 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 43 | loss 9.7048 | train acc 0.250 | test acc 0.250
epoch 44 | loss 9.7045 | train acc 0.250 | test acc 0.250
epoch 45 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 46 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 47 | loss 9.7046 | train acc 0.250 | test acc 0.250
epoch 48 | loss 9.7047 | train acc 0.250 | test acc 0.250
epoch 49 | loss 9.7047 | train acc 0.250 | test acc 0.250

Seed 0 | memory | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8206 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8057 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7950 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7799 | train acc 0.253 | test acc 0.250
epoch 04 | loss 9.4960 | train acc 0.409 | test acc 0.338
epoch 05 | loss 9.0798 | train acc 0.419 | test acc 0.350
epoch 06 | loss 8.7636 | train acc 0.466 | test acc 0.338
epoch 07 | loss 8.5217 | train acc 0.538 | test acc 0.262
epoch 08 | loss 8.1590 | train acc 0.628 | test acc 0.287
epoch 09 | loss 7.8037 | train acc 0.706 | test acc 0.312
epoch 10 | loss 7.4740 | train acc 0.753 | test acc 0.325
epoch 11 | loss 7.0895 | train acc 0.788 | test acc 0.325
epoch 12 | loss 6.7391 | train acc 0.884 | test acc 0.325
epoch 13 | loss 6.3055 | train acc 0.894 | test acc 0.287
epoch 14 | loss 5.8354 | train acc 0.919 | test acc 0.363
epoch 15 | loss 5.4870 | train acc 0.950 | test acc 0.300
epoch 16 | loss 5.0446 | train acc 0.962 | test acc 0.338
epoch 17 | loss 4.6586 | train acc 0.988 | test acc 0.325
epoch 18 | loss 4.3284 | train acc 0.988 | test acc 0.325
epoch 19 | loss 4.0589 | train acc 0.997 | test acc 0.350
epoch 20 | loss 3.8327 | train acc 0.997 | test acc 0.350
epoch 21 | loss 3.6319 | train acc 1.000 | test acc 0.375
epoch 22 | loss 3.4687 | train acc 1.000 | test acc 0.363
epoch 23 | loss 3.3189 | train acc 1.000 | test acc 0.375
epoch 24 | loss 3.2073 | train acc 1.000 | test acc 0.363
epoch 25 | loss 3.1056 | train acc 1.000 | test acc 0.338
epoch 26 | loss 3.0274 | train acc 1.000 | test acc 0.325
epoch 27 | loss 2.9809 | train acc 1.000 | test acc 0.363
epoch 28 | loss 2.9291 | train acc 1.000 | test acc 0.350
epoch 29 | loss 2.8888 | train acc 1.000 | test acc 0.350
epoch 30 | loss 2.8536 | train acc 1.000 | test acc 0.363
epoch 31 | loss 2.8235 | train acc 1.000 | test acc 0.387
epoch 32 | loss 2.7915 | train acc 1.000 | test acc 0.387
epoch 33 | loss 2.7663 | train acc 1.000 | test acc 0.375
epoch 34 | loss 2.7364 | train acc 1.000 | test acc 0.363
epoch 35 | loss 2.7088 | train acc 1.000 | test acc 0.375
epoch 36 | loss 2.6843 | train acc 1.000 | test acc 0.350
epoch 37 | loss 2.6605 | train acc 1.000 | test acc 0.350
epoch 38 | loss 2.6354 | train acc 1.000 | test acc 0.325
epoch 39 | loss 2.6082 | train acc 1.000 | test acc 0.350
epoch 40 | loss 2.5879 | train acc 1.000 | test acc 0.325
epoch 41 | loss 2.5494 | train acc 1.000 | test acc 0.312
epoch 42 | loss 2.5122 | train acc 1.000 | test acc 0.312
epoch 43 | loss 2.4830 | train acc 1.000 | test acc 0.350
epoch 44 | loss 2.4449 | train acc 1.000 | test acc 0.338
epoch 45 | loss 2.4087 | train acc 1.000 | test acc 0.338
epoch 46 | loss 2.3651 | train acc 1.000 | test acc 0.325
epoch 47 | loss 2.3338 | train acc 1.000 | test acc 0.325
epoch 48 | loss 2.3046 | train acc 1.000 | test acc 0.325
epoch 49 | loss 2.2733 | train acc 1.000 | test acc 0.325

Seed 1 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8454 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.8484 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7750 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7434 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.8103 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.8082 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7399 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.5798 | train acc 0.475 | test acc 0.438
epoch 09 | loss 9.3317 | train acc 0.438 | test acc 0.425
epoch 10 | loss 9.0746 | train acc 0.478 | test acc 0.488
epoch 11 | loss 8.7989 | train acc 0.441 | test acc 0.488
epoch 12 | loss 8.5768 | train acc 0.475 | test acc 0.500
epoch 13 | loss 8.3529 | train acc 0.469 | test acc 0.488
epoch 14 | loss 8.1532 | train acc 0.472 | test acc 0.488
epoch 15 | loss 7.9601 | train acc 0.475 | test acc 0.500
epoch 16 | loss 7.8143 | train acc 0.478 | test acc 0.500
epoch 17 | loss 7.6505 | train acc 0.484 | test acc 0.500
epoch 18 | loss 7.5296 | train acc 0.491 | test acc 0.500
epoch 19 | loss 7.3854 | train acc 0.497 | test acc 0.500
epoch 20 | loss 7.2805 | train acc 0.500 | test acc 0.500
epoch 21 | loss 7.1358 | train acc 0.512 | test acc 0.488
epoch 22 | loss 7.0264 | train acc 0.538 | test acc 0.500
epoch 23 | loss 6.9034 | train acc 0.547 | test acc 0.500
epoch 24 | loss 6.7813 | train acc 0.572 | test acc 0.512
epoch 25 | loss 6.6879 | train acc 0.578 | test acc 0.500
epoch 26 | loss 6.5658 | train acc 0.591 | test acc 0.500
epoch 27 | loss 6.4639 | train acc 0.591 | test acc 0.500
epoch 28 | loss 6.3735 | train acc 0.597 | test acc 0.475
epoch 29 | loss 6.1875 | train acc 0.603 | test acc 0.463
epoch 30 | loss 6.0390 | train acc 0.619 | test acc 0.512
epoch 31 | loss 5.9224 | train acc 0.637 | test acc 0.488
epoch 32 | loss 5.7855 | train acc 0.656 | test acc 0.450
epoch 33 | loss 5.6929 | train acc 0.700 | test acc 0.425
epoch 34 | loss 5.5761 | train acc 0.681 | test acc 0.387
epoch 35 | loss 5.4734 | train acc 0.716 | test acc 0.387
epoch 36 | loss 5.3430 | train acc 0.731 | test acc 0.412
epoch 37 | loss 5.2115 | train acc 0.766 | test acc 0.450
epoch 38 | loss 5.0629 | train acc 0.778 | test acc 0.475
epoch 39 | loss 4.9262 | train acc 0.788 | test acc 0.438
epoch 40 | loss 4.8306 | train acc 0.809 | test acc 0.425
epoch 41 | loss 4.7465 | train acc 0.812 | test acc 0.463
epoch 42 | loss 4.5807 | train acc 0.831 | test acc 0.450
epoch 43 | loss 4.4425 | train acc 0.837 | test acc 0.463
epoch 44 | loss 4.2649 | train acc 0.825 | test acc 0.475
epoch 45 | loss 4.1315 | train acc 0.859 | test acc 0.450
epoch 46 | loss 3.9173 | train acc 0.878 | test acc 0.463
epoch 47 | loss 3.7655 | train acc 0.897 | test acc 0.488
epoch 48 | loss 3.5908 | train acc 0.875 | test acc 0.450
epoch 49 | loss 3.4361 | train acc 0.913 | test acc 0.500

Seed 1 | memory | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.8638 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.8170 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.4504 | train acc 0.444 | test acc 0.375
epoch 03 | loss 9.0300 | train acc 0.531 | test acc 0.375
epoch 04 | loss 8.6260 | train acc 0.750 | test acc 0.375
epoch 05 | loss 8.1865 | train acc 0.834 | test acc 0.400
epoch 06 | loss 7.7117 | train acc 0.859 | test acc 0.400
epoch 07 | loss 7.3172 | train acc 0.925 | test acc 0.475
epoch 08 | loss 6.7992 | train acc 0.944 | test acc 0.450
epoch 09 | loss 6.3980 | train acc 0.966 | test acc 0.438
epoch 10 | loss 5.9604 | train acc 0.966 | test acc 0.463
epoch 11 | loss 5.6714 | train acc 0.991 | test acc 0.475
epoch 12 | loss 5.4645 | train acc 0.988 | test acc 0.512
epoch 13 | loss 5.1810 | train acc 0.988 | test acc 0.488
epoch 14 | loss 5.0395 | train acc 0.994 | test acc 0.500
epoch 15 | loss 4.8157 | train acc 0.994 | test acc 0.475
epoch 16 | loss 4.5613 | train acc 0.994 | test acc 0.500
epoch 17 | loss 4.3725 | train acc 0.997 | test acc 0.488
epoch 18 | loss 4.1615 | train acc 1.000 | test acc 0.475
epoch 19 | loss 3.9719 | train acc 1.000 | test acc 0.500
epoch 20 | loss 3.7430 | train acc 1.000 | test acc 0.450
epoch 21 | loss 3.5705 | train acc 1.000 | test acc 0.475
epoch 22 | loss 3.4106 | train acc 1.000 | test acc 0.475
epoch 23 | loss 3.2211 | train acc 1.000 | test acc 0.500
epoch 24 | loss 3.0498 | train acc 1.000 | test acc 0.475
epoch 25 | loss 2.9010 | train acc 1.000 | test acc 0.475
epoch 26 | loss 2.7866 | train acc 1.000 | test acc 0.475
epoch 27 | loss 2.6760 | train acc 1.000 | test acc 0.475
epoch 28 | loss 2.5923 | train acc 1.000 | test acc 0.488
epoch 29 | loss 2.5360 | train acc 1.000 | test acc 0.463
epoch 30 | loss 2.4768 | train acc 1.000 | test acc 0.463
epoch 31 | loss 2.4218 | train acc 1.000 | test acc 0.488
epoch 32 | loss 2.3745 | train acc 1.000 | test acc 0.500
epoch 33 | loss 2.3367 | train acc 1.000 | test acc 0.488
epoch 34 | loss 2.3070 | train acc 1.000 | test acc 0.488
epoch 35 | loss 2.2705 | train acc 1.000 | test acc 0.500
epoch 36 | loss 2.2385 | train acc 1.000 | test acc 0.488
epoch 37 | loss 2.2021 | train acc 1.000 | test acc 0.488
epoch 38 | loss 2.1706 | train acc 1.000 | test acc 0.500
epoch 39 | loss 2.1423 | train acc 1.000 | test acc 0.500
epoch 40 | loss 2.1151 | train acc 1.000 | test acc 0.488
epoch 41 | loss 2.0807 | train acc 1.000 | test acc 0.500
epoch 42 | loss 2.0553 | train acc 1.000 | test acc 0.488
epoch 43 | loss 2.0261 | train acc 1.000 | test acc 0.488
epoch 44 | loss 1.9982 | train acc 1.000 | test acc 0.500
epoch 45 | loss 1.9675 | train acc 1.000 | test acc 0.500
epoch 46 | loss 1.9393 | train acc 1.000 | test acc 0.488
epoch 47 | loss 1.9097 | train acc 1.000 | test acc 0.488
epoch 48 | loss 1.8750 | train acc 1.000 | test acc 0.463
epoch 49 | loss 1.8420 | train acc 1.000 | test acc 0.450

Seed 2 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7537 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7599 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7415 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7387 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7216 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7125 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7073 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.6910 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.6672 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.6448 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.6275 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.6031 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.6168 | train acc 0.269 | test acc 0.250
epoch 14 | loss 9.5444 | train acc 0.312 | test acc 0.275
epoch 15 | loss 9.4790 | train acc 0.341 | test acc 0.275
epoch 16 | loss 9.3682 | train acc 0.363 | test acc 0.287
epoch 17 | loss 9.1826 | train acc 0.366 | test acc 0.300
epoch 18 | loss 8.8850 | train acc 0.412 | test acc 0.350
epoch 19 | loss 8.5704 | train acc 0.475 | test acc 0.450
epoch 20 | loss 8.2346 | train acc 0.488 | test acc 0.475
epoch 21 | loss 7.9335 | train acc 0.497 | test acc 0.475
epoch 22 | loss 7.6369 | train acc 0.494 | test acc 0.475
epoch 23 | loss 7.4300 | train acc 0.494 | test acc 0.475
epoch 24 | loss 7.3637 | train acc 0.500 | test acc 0.475
epoch 25 | loss 7.2344 | train acc 0.503 | test acc 0.475
epoch 26 | loss 7.1263 | train acc 0.519 | test acc 0.500
epoch 27 | loss 7.0713 | train acc 0.509 | test acc 0.488
epoch 28 | loss 6.9892 | train acc 0.559 | test acc 0.488
epoch 29 | loss 7.0027 | train acc 0.581 | test acc 0.512
epoch 30 | loss 6.8922 | train acc 0.553 | test acc 0.538
epoch 31 | loss 6.8836 | train acc 0.625 | test acc 0.550
epoch 32 | loss 6.8105 | train acc 0.566 | test acc 0.475
epoch 33 | loss 6.7884 | train acc 0.591 | test acc 0.550
epoch 34 | loss 6.6967 | train acc 0.591 | test acc 0.538
epoch 35 | loss 6.8297 | train acc 0.578 | test acc 0.475
epoch 36 | loss 6.6093 | train acc 0.622 | test acc 0.525
epoch 37 | loss 6.5136 | train acc 0.628 | test acc 0.512
epoch 38 | loss 6.4224 | train acc 0.631 | test acc 0.512
epoch 39 | loss 6.3928 | train acc 0.631 | test acc 0.538
epoch 40 | loss 6.3001 | train acc 0.650 | test acc 0.525
epoch 41 | loss 6.2170 | train acc 0.666 | test acc 0.538
epoch 42 | loss 6.1402 | train acc 0.672 | test acc 0.512
epoch 43 | loss 6.0854 | train acc 0.675 | test acc 0.512
epoch 44 | loss 6.0613 | train acc 0.706 | test acc 0.525
epoch 45 | loss 5.9432 | train acc 0.722 | test acc 0.500
epoch 46 | loss 5.9139 | train acc 0.719 | test acc 0.550
epoch 47 | loss 5.7566 | train acc 0.719 | test acc 0.575
epoch 48 | loss 5.7358 | train acc 0.775 | test acc 0.562
epoch 49 | loss 5.6705 | train acc 0.734 | test acc 0.587

Seed 2 | memory | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.7610 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7436 | train acc 0.319 | test acc 0.275
epoch 02 | loss 9.7418 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.6262 | train acc 0.403 | test acc 0.325
epoch 04 | loss 9.3879 | train acc 0.453 | test acc 0.338
epoch 05 | loss 9.0252 | train acc 0.478 | test acc 0.350
epoch 06 | loss 8.4438 | train acc 0.663 | test acc 0.350
epoch 07 | loss 8.3953 | train acc 0.706 | test acc 0.338
epoch 08 | loss 7.6599 | train acc 0.731 | test acc 0.412
epoch 09 | loss 7.1559 | train acc 0.750 | test acc 0.363
epoch 10 | loss 6.7518 | train acc 0.769 | test acc 0.412
epoch 11 | loss 6.4754 | train acc 0.863 | test acc 0.412
epoch 12 | loss 6.1286 | train acc 0.881 | test acc 0.400
epoch 13 | loss 5.9017 | train acc 0.878 | test acc 0.450
epoch 14 | loss 5.6250 | train acc 0.938 | test acc 0.450
epoch 15 | loss 5.3027 | train acc 0.931 | test acc 0.488
epoch 16 | loss 4.9924 | train acc 0.959 | test acc 0.463
epoch 17 | loss 4.7166 | train acc 0.972 | test acc 0.475
epoch 18 | loss 4.4042 | train acc 0.972 | test acc 0.463
epoch 19 | loss 4.1648 | train acc 0.975 | test acc 0.463
epoch 20 | loss 3.9301 | train acc 0.981 | test acc 0.488
epoch 21 | loss 3.7014 | train acc 0.991 | test acc 0.450
epoch 22 | loss 3.5494 | train acc 0.988 | test acc 0.475
epoch 23 | loss 3.3429 | train acc 0.997 | test acc 0.475
epoch 24 | loss 3.1168 | train acc 0.997 | test acc 0.488
epoch 25 | loss 2.9643 | train acc 0.997 | test acc 0.500
epoch 26 | loss 2.8382 | train acc 0.997 | test acc 0.488
epoch 27 | loss 2.7558 | train acc 1.000 | test acc 0.512
epoch 28 | loss 2.6833 | train acc 1.000 | test acc 0.488
epoch 29 | loss 2.6263 | train acc 1.000 | test acc 0.475
epoch 30 | loss 2.5881 | train acc 1.000 | test acc 0.475
epoch 31 | loss 2.5403 | train acc 1.000 | test acc 0.463
epoch 32 | loss 2.5009 | train acc 1.000 | test acc 0.463
epoch 33 | loss 2.4603 | train acc 1.000 | test acc 0.463
epoch 34 | loss 2.4298 | train acc 1.000 | test acc 0.450
epoch 35 | loss 2.7831 | train acc 1.000 | test acc 0.400
epoch 36 | loss 2.6055 | train acc 1.000 | test acc 0.425
epoch 37 | loss 2.4737 | train acc 1.000 | test acc 0.475
epoch 38 | loss 2.4083 | train acc 1.000 | test acc 0.525
epoch 39 | loss 2.3507 | train acc 1.000 | test acc 0.500
epoch 40 | loss 2.3013 | train acc 1.000 | test acc 0.463
epoch 41 | loss 2.2598 | train acc 1.000 | test acc 0.463
epoch 42 | loss 2.2222 | train acc 1.000 | test acc 0.463
epoch 43 | loss 2.1863 | train acc 1.000 | test acc 0.450
epoch 44 | loss 2.1501 | train acc 1.000 | test acc 0.450
epoch 45 | loss 2.1210 | train acc 1.000 | test acc 0.438
epoch 46 | loss 2.0943 | train acc 1.000 | test acc 0.450
epoch 47 | loss 2.0568 | train acc 1.000 | test acc 0.438
epoch 48 | loss 2.0192 | train acc 1.000 | test acc 0.463
epoch 49 | loss 1.9955 | train acc 1.000 | test acc 0.475

Seed 3 | raw | feature threshold=0.75 | output threshold=0.75
epoch 00 | loss 9.7704 | train acc 0.250 | test acc 0.250
epoch 01 | loss 9.7640 | train acc 0.250 | test acc 0.250
epoch 02 | loss 9.7570 | train acc 0.250 | test acc 0.250
epoch 03 | loss 9.7503 | train acc 0.250 | test acc 0.250
epoch 04 | loss 9.7462 | train acc 0.250 | test acc 0.250
epoch 05 | loss 9.7412 | train acc 0.250 | test acc 0.250
epoch 06 | loss 9.7360 | train acc 0.250 | test acc 0.250
epoch 07 | loss 9.7324 | train acc 0.250 | test acc 0.250
epoch 08 | loss 9.7303 | train acc 0.250 | test acc 0.250
epoch 09 | loss 9.7261 | train acc 0.250 | test acc 0.250
epoch 10 | loss 9.7233 | train acc 0.250 | test acc 0.250
epoch 11 | loss 9.7210 | train acc 0.250 | test acc 0.250
epoch 12 | loss 9.7194 | train acc 0.250 | test acc 0.250
epoch 13 | loss 9.7175 | train acc 0.250 | test acc 0.250
epoch 14 | loss 9.7151 | train acc 0.250 | test acc 0.250
epoch 15 | loss 9.7140 | train acc 0.250 | test acc 0.250
epoch 16 | loss 9.7126 | train acc 0.250 | test acc 0.250
epoch 17 | loss 9.7122 | train acc 0.250 | test acc 0.250
epoch 18 | loss 9.7104 | train acc 0.250 | test acc 0.250
epoch 19 | loss 9.7102 | train acc 0.250 | test acc 0.250
epoch 20 | loss 9.7089 | train acc 0.250 | test acc 0.250
epoch 21 | loss 9.7088 | train acc 0.250 | test acc 0.250
epoch 22 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 23 | loss 9.7078 | train acc 0.250 | test acc 0.250
epoch 24 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 25 | loss 9.7071 | train acc 0.250 | test acc 0.250
epoch 26 | loss 9.7065 | train acc 0.250 | test acc 0.250
epoch 27 | loss 9.7060 | train acc 0.250 | test acc 0.250
epoch 28 | loss 9.7058 | train acc 0.250 | test acc 0.250
epoch 29 | loss 9.7063 | train acc 0.250 | test acc 0.250
epoch 30 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 31 | loss 9.7053 | train acc 0.250 | test acc 0.250
epoch 32 | loss 9.7054 | train acc 0.250 | test acc 0.250
epoch 33 | loss 9.7055 | train acc 0.250 | test acc 0.250
epoch 34 | loss 9.7057 | train acc 0.250 | test acc 0.250
epoch 35 | loss 9.7050 | train acc 0.250 | test acc 0.250
epoch 36 | loss 9.7051 | train acc 0.250 | test acc 0.250

,seed,input,feature_threshold,output_threshold,best_test_accuracy,best_epoch,spike_accuracy,membrane_accuracy,zero_spike_samples,mean_output_spikes
0,0,raw,0.75,0.75,0.2500,0,0.2500,0.2500,80,0.0000
1,0,memory,0.75,0.75,0.3875,31,0.3875,0.3500,3,3.9000
2,1,raw,0.75,0.75,0.5125,24,0.5125,0.5375,47,1.6750
3,1,memory,0.75,0.75,0.5125,12,0.5125,0.5000,1,3.1625
4,2,raw,0.75,0.75,0.5875,49,0.5875,0.6500,3,2.8875
5,2,memory,0.75,0.75,0.5250,38,0.5250,0.4750,0,5.1375
6,3,raw,0.75,0.75,0.2500,0,0.2500,0.2500,80,0.0000
7,3,memory,0.75,0.75,0.4500,25,0.4500,0.4375,1,3.5750
8,4,raw,0.75,0.75,0.6000,15,0.6000,0.5500,0,3.7750
9,4,memory,0.75,0.75,0.5125,10,0.5125,0.4875,1,3.4000

MEMORY VS RAW BY SEED

input  memory     raw  memory_minus_raw
seed
0      0.3875  0.2500            0.1375
1      0.5125  0.5125            0.0000
2      0.5250  0.5875           -0.0625
3      0.4500  0.2500            0.2000
4      0.5125  0.6000           -0.0875

MEAN RESULTS

                    mean
input
memory            0.4775
raw               0.4400
memory_minus_raw  0.0375